// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using AnalysisITC.AppClasses.AnalysisClasses;
using System.Linq;
using AnalysisITC.AppClasses.AnalysisClasses.Models;

namespace AnalysisITC
{
    public partial class DataAnalysisViewController : NSViewController
    {
        // ── Coordinator ────────────────────────────────────────────────────
        // The workspace owns all analysis state. The controller only translates
        // UI events → workspace calls, and workspace events → UI updates.

        public AnalysisWorkspace Workspace { get; } = new();

        // ── UI helpers ─────────────────────────────────────────────────────

        bool IsGlobalMode => AnalysisModeControl.SelectedSegment == 1;
        bool ShowPeakInfo => PeakInfoScopeButton.State == NSCellStateValue.On;
        bool ShowParameters => ParametersScopeButton.State == NSCellStateValue.On;
        bool SameAxes => AxesScopeButton.State == NSCellStateValue.On;
        bool ShowResidualGraph => ShowResidualGraphButton.State == NSCellStateValue.On;
        bool ScaleToValid => ScaleToValidButton.State == NSCellStateValue.On;
        bool HasActiveExperiments => DataManager.Data.Count(d => d.Include) > 0;
        NSStackView constraintOptionsStackView;

        AnalysisModel ModelFromSegmentedControl => (int)ModelTypeControl.SelectedSegment switch
        {
            1 => AnalysisModel.TwoSetsOfSites,
            2 => AnalysisModel.CompetitiveBinding,
            3 => AnalysisModel.Dissociation,
            _ => AnalysisModel.OneSetOfSites,
        };

        // ── Static graph invalidation (preserved for cross-VC callers) ─────

        public static event EventHandler Invalidate;
        public static void InvalidateGraph() => Invalidate?.Invoke(null, null);

        // ── Lifecycle ──────────────────────────────────────────────────────

        public DataAnalysisViewController(IntPtr handle) : base(handle) { }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Workspace events
            Workspace.ContextRebuilt += OnContextRebuilt;

            // Solver events
            SolverInterface.AnalysisFinished += OnAnalysisFinished;
            SolverInterface.AnalysisStepFinished += (_, _) => GraphView.Invalidate();
            SolverInterface.ErrorEstimationIterationCompleted += OnErrorIteration;
            SolverInterface.SolverUpdated += (_, e) => e.SendToStatusBar();

            // Data events
            DataManager.SelectionDidChange += OnSelectionChanged;
            DataManager.DataDidChange += OnDataChanged;
            DataManager.DataInclusionDidChange += OnDataChanged;
            DataProcessor.ProcessingCompleted += (_, _) => Workspace.TryRebuild();

            // Misc events
            Invalidate += (_, _) => GraphView.Invalidate();
            AnalysisGlobalModeOptionsView2.ParameterContraintUpdated += OnConstraintUpdated;
            AppDelegate.StartPrintOperation += OnPrintOperation;
            AnalysisITCDataSource.SourceWasSorted += (_, _) => RefreshGlobalModeControls();

            EnsureConstraintOptionsStackView();
        }

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            PeakInfoScopeButton.State = AnalysisGraphView.ShowPeakInfo ? NSCellStateValue.On : NSCellStateValue.Off;
            ParametersScopeButton.State = AnalysisGraphView.ShowFitParameters ? NSCellStateValue.On : NSCellStateValue.Off;
            AxesScopeButton.State = AnalysisGraphView.UseUnifiedAxes ? NSCellStateValue.On : NSCellStateValue.Off;
            ShowResidualGraphButton.State = AnalysisGraphView.ShowResidualGraph ? NSCellStateValue.On : NSCellStateValue.Off;
            LineSmoothnessControl.SelectedSegment = AnalysisGraphView.LineSmoothness == GraphBase.LineSmoothness.Linear ? 0 : 1;

            GraphView.Initialize(DataManager.Current);
        }

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            RefreshGlobalModeControls();
            Workspace.TryRebuild();
        }

        // ── UI action handlers ─────────────────────────────────────────────

        partial void AnalysisModeClicked(NSSegmentedControl sender)
        {
            Workspace.SetGlobalMode(IsGlobalMode);
            RefreshGlobalModeControls();
        }

        partial void AnalysisModelClicked(NSSegmentedControl sender)
        {
            Workspace.SetModelType(ModelFromSegmentedControl);
            RefreshModelAvailability();
        }

        partial void FitSimplex(NSObject sender) => RunFit();
        partial void FitLM(NSObject sender) => RunFit();

        partial void FeatureDrawControlClicked(NSSegmentedControl sender)
        {
            AnalysisGraphView.ShowPeakInfo = sender.IsSelectedForSegment(0);
            AnalysisGraphView.ShowFitParameters = sender.IsSelectedForSegment(1);
            AnalysisGraphView.UseUnifiedAxes = sender.IsSelectedForSegment(2);

            GraphView.Invalidate();
        }

        partial void ScopeButtonClicked(NSButton sender)
        {
            AnalysisGraphView.ShowPeakInfo = ShowPeakInfo;
            AnalysisGraphView.ShowFitParameters = ShowParameters;
            AnalysisGraphView.UseUnifiedAxes = SameAxes;
            AnalysisGraphView.ShowResidualGraph = ShowResidualGraph;
            AnalysisGraphView.ScaleToValidPoints = ScaleToValid;

            GraphView.Invalidate();
        }

        partial void LineSmoothnessAction(NSObject sender)
        {
            AnalysisGraphView.LineSmoothness = LineSmoothnessControl.SelectedSegment == 0
                ? GraphBase.LineSmoothness.Linear
                : GraphBase.LineSmoothness.Smooth;
            ScopeButtonClicked(null);
        }

        // ── Data / selection changes ───────────────────────────────────────

        void OnSelectionChanged(object sender, ExperimentData e)
        {
            Workspace.TryRebuild();
            RefreshGlobalModeControls();
            GraphView.Initialize(e);
        }

        void OnDataChanged(object sender, ExperimentData e)
        {
            Workspace.TryRebuild();
            RefreshGlobalModeControls();
        }

        // ── Workspace callbacks ────────────────────────────────────────────

        void OnContextRebuilt(object sender, EventArgs e)
        {
            RebuildConstraintOptionViews();
            RefreshModelAvailability();
            StatusBarManager.Invalidate();
            GraphView.Invalidate();
        }

        // ── Constraint UI ──────────────────────────────────────────────────

        void OnConstraintUpdated(object sender, EventArgs e)
        {
            // AnalysisGlobalModeOptionsView2 mutates GlobalModelParameters.Constraints directly.
            // Read those back into session state, then rebuild so the new global parameter
            // table is derived from the new constraints.
            if (!Workspace.IsReady || !Workspace.Session.IsGlobal) return;

            Workspace.ImportConstraints(Workspace.Context.GlobalModelParameters.Constraints);
            Workspace.TryRebuild();
        }

        void RebuildConstraintOptionViews()
        {
            EnsureConstraintOptionsStackView();
            ClearConstraintOptionViews();

            if (Workspace.IsReady && Workspace.Session.IsGlobal)
            {
                var ctx = Workspace.Context;

                foreach (var (paramType, constraintOptions) in ctx.ExposedConstraintOptions)
                {
                    var control = new AnalysisGlobalModeOptionsView2(
                        new CoreGraphics.CGRect(0, 0, OptionsStackView.Frame.Width, 19));
                    control.Setup(paramType, constraintOptions.ToList(), ctx.GlobalModelParameters);
                    constraintOptionsStackView.AddArrangedSubview(control);
                }
            }

            constraintOptionsStackView.Hidden = constraintOptionsStackView.Views.Length == 0;
            constraintOptionsStackView.Layout();
            OptionsStackView.Layout();
        }

        void EnsureConstraintOptionsStackView()
        {
            if (constraintOptionsStackView != null) return;

            constraintOptionsStackView = new NSStackView(new CoreGraphics.CGRect(0, 0, OptionsStackView.Frame.Width, 0))
            {
                Orientation = NSUserInterfaceLayoutOrientation.Vertical,
                Distribution = NSStackViewDistribution.Fill,
                Alignment = NSLayoutAttribute.Width,
                Spacing = 1,
                DetachesHiddenViews = true,
                TranslatesAutoresizingMaskIntoConstraints = false,
                Hidden = true,
            };
            constraintOptionsStackView.SetContentHuggingPriorityForOrientation(249, NSLayoutConstraintOrientation.Horizontal);
            constraintOptionsStackView.SetContentHuggingPriorityForOrientation(1000, NSLayoutConstraintOrientation.Vertical);
            constraintOptionsStackView.SetClippingResistancePriority(750, NSLayoutConstraintOrientation.Horizontal);

            OptionsStackView.InsertArrangedSubview(constraintOptionsStackView, 2);
            constraintOptionsStackView.WidthAnchor.ConstraintEqualToAnchor(OptionsStackView.WidthAnchor).Active = true;
        }

        void ClearConstraintOptionViews()
        {
            foreach (var view in constraintOptionsStackView.Views.ToArray())
            {
                constraintOptionsStackView.RemoveView(view);
                view.Dispose();
            }
        }

        // ── Fitting ────────────────────────────────────────────────────────

        void RunFit()
        {
            if (!HasActiveExperiments)
                return;

            if (!AnalysisBuilder.IsModelAvailable(ModelFromSegmentedControl, IsGlobalMode))
            {
                AppEventHandler.DisplayHandledException(new HandledException(
                    HandledException.Severity.Message,
                    "Model Not Available",
                    "The current data selection does not support analysis using the selected model"));
                return;
            }

            try
            {
                AppEventHandler.PrintAndLog("Start Analysis");
                ToggleFitButtons(false);

                // Ensure we have a context even if no data-change event fired yet
                if (!Workspace.IsReady) Workspace.Rebuild();

                var solver = Workspace.PrepareForSolve();
                solver.SolverAlgorithm = FittingOptionsController.Algorithm;
                solver.ErrorEstimationMethod = FittingOptionsController.ErrorEstimationMethod;
                solver.BootstrapIterations = FittingOptionsController.BootstrapIterations;

                solver.Analyze();

                // Persist converged values so the next rebuild starts from the fit result,
                // but do NOT rebuild now — the current context IS the fitted model.
                // Workspace.PersistFittedParameters(); TODO figure out if this is relevant
            }
            catch (Exception ex)
            {
                AppEventHandler.DisplayHandledException(ex);
                StatusBarManager.ClearAppStatus();
                ToggleFitButtons(true);
            }
        }

        // ── Solver event handlers ──────────────────────────────────────────

        void OnAnalysisFinished(object sender, SolverConvergence e)
        {
            AppEventHandler.PrintAndLog("Analysis Ended: " + e.Termination, 0);
            AppEventHandler.PrintAndLog("Iterations: " + e.Iterations, 1);
            AppEventHandler.PrintAndLog("Time: " + e.Time.TotalMilliseconds + "ms", 1);
            AppEventHandler.PrintAndLog("Error Time: " + e.ErrorEstimationTime.TotalMilliseconds + "ms", 1);
            AppEventHandler.PrintAndLog("Message: " + e.Message, 1);
            AppEventHandler.PrintAndLog("Failure Reason: " + e.FailureReason, 1);
            AppEventHandler.PrintAndLog("Error Summary: " + e.ErrorEstimationSummary, 1);
            AppEventHandler.PrintAndLog("Error Estimation: " + e.ErrorEstimationOutcome, 1);
            AppEventHandler.PrintAndLog("Stopped: " + e.Stopped, 1);
            AppEventHandler.PrintAndLog("Failed:  " + e.Failed, 1);

            StatusBarManager.ClearAppStatus();
            if (e.ErrorEstimationOutcome != ErrorEstimationOutcome.None) StatusBarManager.SetStatus($"{e.ErrorEstimationSummary}", 10000);
            if (e.Success) StatusBarManager.SetStatus($"{e.Algorithm.GetProperties().ShortName} | RMSD = {e.Loss:G4}", 8000);
            StatusBarManager.SetStatus($"{e.Iterations} iterations | {TimeUnitAttribute.FormatTimeSpanShort(e.TotalTime)}", 6000);
            StatusBarManager.SetStatus($"{e.Message}", 3000);

            GraphView.Invalidate();
            ToggleFitButtons(true);
        }

        void OnErrorIteration(object sender, Tuple<int, int, float> e)
        {
            StatusBarManager.SetProgress(e.Item3);
            StatusBarManager.SetStatus("Estimating Errors...", 0, 2);
            StatusBarManager.SetSecondaryStatus(e.Item1 + "/" + e.Item2, 0);
        }

        // ── Misc ───────────────────────────────────────────────────────────

        void OnPrintOperation(object sender, EventArgs e)
        {
            if (StateManager.CurrentState != ProgramState.Analyze) return;
            GraphView.Print();
        }

        void RefreshGlobalModeControls()
        {
            AnalysisModeControl.SetEnabled(true, 1);
            RefreshModelAvailability();
        }

        void RefreshModelAvailability()
        {
            var models = new[] { AnalysisModel.OneSetOfSites, AnalysisModel.TwoSetsOfSites, AnalysisModel.CompetitiveBinding, AnalysisModel.Dissociation };
            bool isGlobal = IsGlobalMode;

            for (int i = 0; i < models.Length; i++)
                ModelTypeControl.SetEnabled(AnalysisBuilder.IsModelAvailable(models[i], isGlobal), i);

            ToggleFitButtons(true);
        }

        void ToggleFitButtons(bool enable)
        {
            bool canFit = enable && CanRunFit();
            FitSimplexButton.Enabled = canFit;
            FitLMButton.Enabled = canFit;
        }

        bool CanRunFit()
        {
            return HasActiveExperiments && AnalysisBuilder.IsModelAvailable(ModelFromSegmentedControl, IsGlobalMode);
        }

        // ── Cleanup ────────────────────────────────────────────────────────

        bool _eventsUnsubscribed;

        void UnsubscribeEvents()
        {
            if (_eventsUnsubscribed) return;
            _eventsUnsubscribed = true;

            Workspace.ContextRebuilt -= OnContextRebuilt;
            SolverInterface.AnalysisFinished -= OnAnalysisFinished;
            SolverInterface.ErrorEstimationIterationCompleted -= OnErrorIteration;
            DataManager.SelectionDidChange -= OnSelectionChanged;
            DataManager.DataDidChange -= OnDataChanged;
            DataManager.DataInclusionDidChange -= OnDataChanged;
            AnalysisGlobalModeOptionsView2.ParameterContraintUpdated -= OnConstraintUpdated;
            AppDelegate.StartPrintOperation -= OnPrintOperation;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) UnsubscribeEvents();

            base.Dispose(disposing);
        }
    }
}