// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class FinalFigureViewController : NSViewController
	{
        bool _eventsUnsubscribed = false;
        bool _isSyncingEmbeddedOptions = false;

        public FinalFigureViewController (IntPtr handle) : base (handle)
		{
            AppDelegate.StartPrintOperation += AppDelegate_StartPrintOperation;
		}

        private void AppDelegate_StartPrintOperation(object sender, EventArgs e)
        {
            if (StateManager.CurrentState != ProgramState.Publish) return;

            FinalFigureGraph.Print();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            FinalFigureGraphView.PlotSizeChanged += FinalFigureGraphView_PlotSizeChanged;
            SyncEmbeddedOptions();
        }

        public override void ViewDidAppear()
        {
            SyncEmbeddedOptions();
            FinalFigureGraphView.Invalidate();
        }

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();
            SyncEmbeddedOptions();
        }

        private void FinalFigureGraphView_PlotSizeChanged(object sender, EventArgs e)
        {
            var x = BoxView.Frame.Width / 2 - FinalFigureGraph.Frame.Width / 2;
            var y = BoxView.Frame.Height / 2 - FinalFigureGraph.Frame.Height / 2;

            FinalFigureGraph.SetFrameOrigin(new CoreGraphics.CGPoint(x, y));
        }

        partial void ExportGraphButtonClick(NSObject sender)
        {
            if (EmbeddedExportSelectionControl == null)
            {
                FinalFigureGraph.Export();
                return;
            }

            FinalFigureGraphView.Export((ExportDataSelection)(int)EmbeddedExportSelectionControl.SelectedSegment);
        }

        partial void PublishOptionsTabControlChanged(NSObject sender)
        {
            if (PublishOptionsTabView == null || PublishOptionsTabControl == null) return;

            PublishOptionsTabView.SelectAt((int)PublishOptionsTabControl.SelectedSegment);
            SyncEmbeddedOptions();
        }

        partial void ControlChanged(NSObject sender)
        {
            ApplyEmbeddedOptions();
        }

        partial void ControlClicked(NSObject sender)
        {
            ApplyEmbeddedOptions();
        }

        partial void ParameterOptionAction(NSObject sender)
        {
            if (_isSyncingEmbeddedOptions) return;

            FinalFigureOptionsController.ToggleParameterOption(sender, EmbeddedParameterDisplayOptionsControl);
            FinalFigureGraphView.Invalidate();
            SyncEmbeddedOptions();
        }

        partial void AttributeOptionAction(NSObject sender)
        {
            if (_isSyncingEmbeddedOptions) return;

            FinalFigureOptionsController.ToggleAttributeOption(sender, EmbeddedAttributeDisplayOptionsControl);
            FinalFigureGraphView.Invalidate();
            SyncEmbeddedOptions();
        }

        [Export("tabView:didSelectTabViewItem:")]
        public void DidSelect(NSTabView tabView, NSTabViewItem item)
        {
            if (tabView != PublishOptionsTabView || item == null) return;

            var selectedIndex = (int)tabView.IndexOf(item);
            PublishOptionsTabControl?.SelectSegment(selectedIndex);
            SyncEmbeddedOptions();
        }

        void ApplyEmbeddedOptions()
        {
            if (_isSyncingEmbeddedOptions) return;

            FinalFigureOptionsController.ApplyGeneral(EmbeddedGeneralControls);
            FinalFigureOptionsController.ApplyData(EmbeddedDataControls);
            FinalFigureOptionsController.ApplyFit(EmbeddedFitControls);

            FinalFigureGraphView.Invalidate();
        }

        void SyncEmbeddedOptions()
        {
            if (_isSyncingEmbeddedOptions) return;

            try
            {
                _isSyncingEmbeddedOptions = true;

                if (PublishOptionsTabView != null && PublishOptionsTabControl != null)
                {
                    var selectedItem = PublishOptionsTabView.Selected;
                    if (selectedItem != null)
                    {
                        PublishOptionsTabControl.SelectSegment((int)PublishOptionsTabView.IndexOf(selectedItem));
                    }
                }

                FinalFigureOptionsController.SyncGeneral(EmbeddedGeneralControls);
                FinalFigureOptionsController.SyncData(EmbeddedDataControls);
                FinalFigureOptionsController.SyncFit(EmbeddedFitControls);
            }
            finally
            {
                _isSyncingEmbeddedOptions = false;
            }
        }

        FinalFigureOptionsController.GeneralControls EmbeddedGeneralControls => new()
        {
            ShowDataGraphControl = EmbeddedShowDataGraphControl,
            EnergyUnitControl = EmbeddedEnergyUnitControl,
            TimeUnitControl = EmbeddedTimeUnitControl,
            SanitizeTicks = EmbeddedSanitizeTicks,
            WidthLabel = EmbeddedWidthLabel,
            HeightLabel = EmbeddedHeightLabel,
            ShowParametersControl = EmbeddedShowParametersControl,
            ShowTextUncertaintiesControl = EmbeddedShowTextUncertaintiesControl,
            TextUncertaintyStyleControl = EmbeddedTextUncertaintyStyleControl,
            InformationBoxPositionControl = EmbeddedInformationBoxPositionControl,
            ParameterDisplayOptionsControl = EmbeddedParameterDisplayOptionsControl,
            AttributeDisplayOptionsControl = EmbeddedAttributeDisplayOptionsControl,
            SyringeNameField = EmbeddedSyringeNameField,
            CellNameField = EmbeddedCellNameField,
            UseNameAttributes = EmbeddedUseNameAttributes,
            NameDisplayModeControl = EmbeddedNameDisplayModeControl,
            ShowAxisTitles = EmbeddedShowAxisTitles,
        };

        FinalFigureOptionsController.DataControls EmbeddedDataControls => new()
        {
            PowerAxisTitleLabel = EmbeddedPowerAxisTitleLabel,
            TimeAxisTitleLabel = EmbeddedTimeAxisTitleLabel,
            XTickLabel = EmbeddedDataXTickLabel,
            XTickStepper = EmbeddedDataXTickStepper,
            YTickLabel = EmbeddedDataYTickLabel,
            YTickStepper = EmbeddedDataYTickStepper,
            XMinField = EmbeddedDataXMinField,
            XMaxField = EmbeddedDataXMaxField,
            YMinField = EmbeddedDataYMinField,
            YMaxField = EmbeddedDataYMaxField,
            UnifiedPowerAxis = EmbeddedUnifiedPowerAxis,
            DrawCorrected = EmbeddedDrawCorrected,
            DrawBaseline = EmbeddedDrawBaseline,
            BaselineStyleControl = EmbeddedBaselineStyleControl,
            BaselineThicknessControl = EmbeddedBaselineThicknessControl,
            BaselineThicknessLabel = EmbeddedBaselineThicknessLabel,
        };

        FinalFigureOptionsController.FitControls EmbeddedFitControls => new()
        {
            EnthalpyAxisTitleLabel = EmbeddedEnthalpyAxisTitleLabel,
            YAxisTickStepper = EmbeddedFitYTickStepper,
            YTickLabel = EmbeddedFitYTickLabel,
            MolarRatioAxisTitleLabel = EmbeddedMolarRatioAxisTitleLabel,
            XAxisTickStepper = EmbeddedFitXTickStepper,
            XTickLabel = EmbeddedFitXTickLabel,
            XMinField = EmbeddedFitXMinField,
            XMaxField = EmbeddedFitXMaxField,
            YMinField = EmbeddedFitYMinField,
            YMaxField = EmbeddedFitYMaxField,
            SplineInterpolationControl = EmbeddedSplineInterpolationControl,
            SymbolControl = EmbeddedSymbolControl,
            SymbolSizeLabel = EmbeddedSymbolSizeLabel,
            SymbolSizeStepper = EmbeddedSymbolSizeStepper,
            UnifiedHeatAxis = EmbeddedUnifiedHeatAxis,
            UnifiedMolarRatioAxis = EmbeddedUnifiedMolarRatioAxis,
            ShowResiduals = EmbeddedShowResiduals,
            AddGapToResidualPlot = EmbeddedAddGapToResidualPlot,
            HideBadData = EmbeddedHideBadData,
            DrawZeroLine = EmbeddedDrawZeroLine,
            DrawErrorBars = EmbeddedDrawErrorBars,
            BadDataErrorBars = EmbeddedBadDataErrorBars,
            DrawConfidence = EmbeddedDrawConfidence,
            DrawOffsetCorrected = EmbeddedDrawOffsetCorrected,
        };

        public override void ViewWillLayout()
        {
            var x = BoxView.Frame.Width / 2 - FinalFigureGraph.Frame.Width / 2;
            var y = BoxView.Frame.Height / 2 - FinalFigureGraph.Frame.Height / 2;

            FinalFigureGraph.SetFrameOrigin(new CoreGraphics.CGPoint(x, y));

            base.ViewWillLayout();
        }

        void UnsubscribeEvents()
        {
            if (_eventsUnsubscribed) return;
            _eventsUnsubscribed = true;

            FinalFigureGraphView.PlotSizeChanged -= FinalFigureGraphView_PlotSizeChanged;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                UnsubscribeEvents();

            base.Dispose(disposing);
        }
    }
}
