// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

using AnalysisITC.Core.Application;
using AnalysisITC.Core.Analysis;
using AnalysisITC.Core.Analysis.Models;
using AnalysisITC.Core.Data;
using AnalysisITC.Core.DataReaders;
using AnalysisITC.Core.Export;
using AnalysisITC.Core.Numerics;
using AnalysisITC.Core.Presentation;
using AnalysisITC.Core.Processing;
using AnalysisITC.Core.Units;
using AnalysisITC.Core.Utilities;

namespace AnalysisITC
{
	public partial class BaselineOptionsPopoverViewController : NSViewController
	{
		ExperimentData Data => DataManager.Current;

        public static event EventHandler Updated;

		public BaselineOptionsPopoverViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            SplinePointsSlider.MinValue = SplineInterpolator.MinimumPointsPerInjection;
            SplinePointsSlider.MaxValue = SplineInterpolator.MaximumPointsPerInjection;
            SplinePointsSlider.IntValue = SplinePointsValue;

            if (Data.Processor.Interpolator != null)
            {
                LockButton.Title = Data.Processor.IsLocked ? "Unlock Processor" : "Lock Processor";
                ToSplineButton.Enabled = Data.Processor.Interpolator is not SplineInterpolator;
            }
            else
            {
                LockButton.Enabled = false;
                ToSplineButton.Enabled = false;
            }
        }

        int SplinePointsValue => ClampSplinePoints(Data?.Processor?.Interpolator is SplineInterpolator splineInterpolator ? splineInterpolator.PointsPerInjection : SplineInterpolator.DefaultPointsPerInjection);

        partial void SplinePointsSliderChanged(NSSlider sender)
        {
            SplineInterpolator.DefaultPointsPerInjection = sender.IntValue;
            sender.IntValue = SplineInterpolator.DefaultPointsPerInjection;

            if (Data?.Processor?.Interpolator is SplineInterpolator splineInterpolator)
            {
                splineInterpolator.PointsPerInjection = SplineInterpolator.DefaultPointsPerInjection;
                _ = Data.Processor.ProcessData();
            }
        }

        partial void LockAction(NSObject sender)
        {
            Data.Processor.ToggleLock();

            Updated?.Invoke(this, null);

            DismissViewController(this);
        }

        partial void SplineAction(NSObject sender)
        {
            SplineInterpolator.DefaultPointsPerInjection = SplinePointsSlider.IntValue;

            Data.Processor.Interpolator.ConvertToSpline(SplineInterpolator.DefaultPointsPerInjection);

            DismissViewController(this);
        }

        static int ClampSplinePoints(int value) => Math.Min(SplineInterpolator.MaximumPointsPerInjection, Math.Max(SplineInterpolator.MinimumPointsPerInjection, value));

        partial void CopyToAllAction(NSObject sender)
        {
            DataManager.CopySelectedProcessToAll();
        }

        partial void CopyToNonProcessed(NSObject sender)
        {
            DataManager.CopySelectedProcessToNonProcessed();
        }
    }
}
