// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AnalysisITC.UI.MacOS;
using AnalysisITC.Core.Utilities;

using AnalysisITC.Core.Application;
using AnalysisITC.Core.Analysis;
using AnalysisITC.Core.Analysis.Models;
using AnalysisITC.Core.Data;
using AnalysisITC.Core.DataReaders;
using AnalysisITC.Core.Export;
using AnalysisITC.Core.Numerics;
using AnalysisITC.Core.Presentation;
using AnalysisITC.Core.Processing;
using AnalysisITC.Core.Units;

namespace AnalysisITC
{
	public partial class AnalysisResultView : NSView
	{
        public static event EventHandler<AnalysisResult> ExpandDataButtonClicked;

        AnalysisResult data;
        Action<ITCDataContainer> removeRequested;

        public AnalysisResultView (IntPtr handle) : base (handle)
		{
		}

        internal void Setup(AnalysisResult analysisResult, Action<ITCDataContainer> removeRequested)
        {
            this.data = analysisResult;
            this.removeRequested = removeRequested;

            ResultTitleLabel.StringValue = analysisResult.Name;
            ResultContentLabel.LineBreakMode = NSLineBreakMode.TruncatingTail;
            ResultContentLabel.Cell.LineBreakMode = NSLineBreakMode.TruncatingTail;

            var attstring = AnalysisITC.UI.MacOS.MacStrings.FromMarkDownString(analysisResult.GetListDescriptionString(), ResultContentLabel.Font);

            ResultContentLabel.AttributedStringValue = WithTruncatingLineBreaks(attstring);
        }

        NSAttributedString WithTruncatingLineBreaks(NSAttributedString attributedString)
        {
            var mutable = new NSMutableAttributedString(attributedString);
            var range = new NSRange(0, mutable.Length);
            var paragraph = new NSMutableParagraphStyle
            {
                LineBreakMode = NSLineBreakMode.TruncatingTail,
            };

            mutable.AddAttribute(NSStringAttributeKey.ParagraphStyle, paragraph, range);

            return mutable;
        }

        partial void ViewResultClick(NSObject sender)
        {
            ExpandDataButtonClicked?.Invoke(this, data);
        }

        partial void RemoveButtonClick(NSObject sender)
        {
            if (data == null) return;

            removeRequested?.Invoke(data);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                data = null;
                removeRequested = null;
            }

            base.Dispose(disposing);
        }
    }
}
