// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

using AnalysisITC.Core.Application;
using AnalysisITC.Core.Analysis;
using AnalysisITC.Core.Analysis.Models;
using AnalysisITC.Core.Data;
using AnalysisITC.Core.DataReaders;
using AnalysisITC.Core.Export;
using AnalysisITC.Core.Numerics;
using AnalysisITC.Core.Presentation;
using AnalysisITC.Core.Processing;
using AnalysisITC.Core.Units;
using AnalysisITC.Core.Utilities;

namespace AnalysisITC
{
	public partial class ExperimentListViewController : NSViewController
	{
		public ExperimentListViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            var result = DataManager.SourceItems[DataManager.SelectedContentIndex];

            if (result is not AnalysisResult) throw new Exception("Selected item not analysis result");

            var analysisresult = result as AnalysisResult;

            Label.StringValue = "";
            Label.AttributedStringValue = AnalysisResultValidityPresentation.ReportText(analysisresult, Label.Font);

            ExperimentListLabel.StringValue = "";
            ExperimentListLabel.AttributedStringValue = AnalysisResultValidityPresentation.ExperimentListText(analysisresult, ExperimentListLabel.Font);
        }
    }
}
