// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Linq;

namespace AnalysisITC
{
	public partial class DataProcessingViewControllet : NSViewController
	{
        ExperimentData Data => DataManager.Current;
        DataProcessor Processor => Data?.Processor;

        bool ShowBaseline => BaselineScopeButton.State == NSCellStateValue.On;
        bool ShowIntegrationRange => IntegrationScopeButton.State == NSCellStateValue.On;
        bool Corrected => CorrectedScopeButton.State == NSCellStateValue.On;

        public DataProcessingViewControllet (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            DataManager.SelectionDidChange += OnSelectionChanged;
            DataProcessor.BaselineInterpolationCompleted += OnInterpolationCompleted;

            BaselineScopeButton.State = NSCellStateValue.On;
            IntegrationScopeButton.State = NSCellStateValue.On;
        }

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            UpdateUI();

            UpdateSliderLabels();

            BaselineGraphView.Initialize(DataManager.Current);

            BaselineGraphView.SetFeatureVisibility(ShowBaseline, ShowIntegrationRange, Corrected);
        }

        void UpdateUI()
        {
            if (Data == null || Processor.BaselineType == BaselineInterpolatorTypes.None)
            {
                SetSelectedSegment(InterpolatorTypeControl, -1);

                SplineAlgorithmView.Hidden = true;
                SplineBaselineFractionView.Hidden = true;
                SplineHandleModeView.Hidden = true;
                PolynomialDegreeView.Hidden = true;
                ZLimitView.Hidden = true;
            }
            else
            {
                SetSelectedSegment(InterpolatorTypeControl, (int)Processor.BaselineType);

                switch (Processor.BaselineType)
                {
                    case BaselineInterpolatorTypes.Spline:
                        SplineAlgorithmView.Hidden = false;
                        SplineHandleModeView.Hidden = false;
                        SplineBaselineFractionView.Hidden = false;
                        PolynomialDegreeView.Hidden = true;
                        ZLimitView.Hidden = true;
                        SetSelectedSegment(SplineAlgoControl, (int)(Data.Processor.Interpolator as SplineInterpolator).Algorithm);
                        SetSelectedSegment(SplineHandleModeControl, (int)(Data.Processor.Interpolator as SplineInterpolator).HandleMode);
                        SplineFractionSliderControl.FloatValue = (Data.Processor.Interpolator as SplineInterpolator).FractionBaseline;
                        break;
                    case BaselineInterpolatorTypes.ASL:
                        SplineAlgorithmView.Hidden = true;
                        SplineHandleModeView.Hidden = true;
                        SplineBaselineFractionView.Hidden = true;
                        PolynomialDegreeView.Hidden = true;
                        ZLimitView.Hidden = true;
                        break;
                    case BaselineInterpolatorTypes.Polynomial:
                        SplineAlgorithmView.Hidden = true;
                        SplineHandleModeView.Hidden = true;
                        SplineBaselineFractionView.Hidden = true;
                        PolynomialDegreeView.Hidden = false;
                        ZLimitView.Hidden = false;
                        PolynomialDegreeSlider.IntValue = (Data.Processor.Interpolator as PolynomialLeastSquaresInterpolator).Degree;
                        ZLimitSlider.DoubleValue = (Data.Processor.Interpolator as PolynomialLeastSquaresInterpolator).ZLimit;
                        break;
                }

                
                if (Data.Injections.Count > 0)
                {
                    IntegrationLengthControl.MaxValue = Data.Injections.Max(inj => inj.Delay);
                    IntegrationDelayControl.FloatValue = Data.Injections.Last().IntegrationStartDelay;
                    if (Data.UseIntegrationFactorLength) IntegrationLengthControl.FloatValue = FactorToSlider(Data.IntegrationLengthFactor);
                    else IntegrationLengthControl.FloatValue = Data.Injections.Last().IntegrationLength;
                }

                InjectionViewSegControl.Enabled = Data.Injections.Count > 0;
                DataZoomSegControl.Enabled = true;

                InjectionViewSegControl.SetLabel((BaselineGraphView.SelectedPeak + 1).ToString(), 1);

                UseFactorSwitch.State = Data.UseIntegrationFactorLength ? 1 : 0;
            }

            UpdateSliderLabels();

            ConfirmProcessingButton.Enabled = DataManager.AllDataIsBaselineProcessed;
        }

        void SetSelectedSegment(NSSegmentedControl control, int segment)
        {
            for (int i = 0; i < control.SegmentCount; i++) control.SetSelected(false, i);

            if (segment > -0.5) control.SetSelected(true, segment);
        }

        void UpdateSliderLabels()
        {
            IntegrationStartDelayLabel.StringValue = (IntegrationDelayControl.FloatValue).ToString("F1") + "s";
            if (Data != null && Data.UseIntegrationFactorLength)
            {
                var factor = SliderToFactor();
                IntegrationLengthLabel.StringValue = factor.ToString("G2") + "x";
            }
            else IntegrationLengthLabel.StringValue = (IntegrationLengthControl.FloatValue).ToString("F1") + "s";
            SplineBaselineFractionControl.StringValue = (SplineFractionSliderControl.FloatValue * 100).ToString("##0") + " %";
            PolynomialDegreeLabel.StringValue = PolynomialDegreeSlider.IntValue.ToString();
            ZLimitLabel.StringValue = ZLimitSlider.FloatValue.ToString("G3");
        }

        #region Processing Baseline

        partial void InterplolatorClicked(NSSegmentedControl sender)
        {
            Processor.InitializeBaseline((BaselineInterpolatorTypes)(int)sender.SelectedSegment);

            UpdateUI();

            UpdateProcessing();
        }

        partial void SplineAlgoClicked(NSSegmentedControl sender)
        {
            (Processor.Interpolator as SplineInterpolator).Algorithm = (SplineInterpolator.SplineInterpolatorAlgorithm)(int)sender.SelectedSegment;

            UpdateProcessing();
        }

        partial void SplineHandleModeControlClicked(NSSegmentedControl sender)
        {
            (Processor.Interpolator as SplineInterpolator).HandleMode = (SplineInterpolator.SplineHandleMode)(int)sender.SelectedSegment;

            UpdateProcessing();
        }

        partial void SplineBaselineFractionSliderChanged(NSSlider sender)
        {
            (Processor.Interpolator as SplineInterpolator).FractionBaseline = sender.FloatValue;

            UpdateSliderLabels();

            UpdateProcessing();
        }

        partial void PolynomialDegreeChanged(NSSlider sender)
        {
            (Processor.Interpolator as PolynomialLeastSquaresInterpolator).Degree = sender.IntValue;

            UpdateSliderLabels();

            UpdateProcessing();
        }

        partial void ZLimitChanged(NSSlider sender)
        {
            (Processor.Interpolator as PolynomialLeastSquaresInterpolator).ZLimit = sender.FloatValue;

            UpdateSliderLabels();

            UpdateProcessing();
        }

        partial void ApplyToAllSwitchToggled(NSSwitch sender)
        {
            
        }

        partial void CopySettingsToAllClicked(NSObject sender)
        {
            DataManager.CopySelectedProcessToAll();
        }

        #endregion

        #region Processing Injections

        partial void IntegrationStartTimeSliderChanged(NSSlider sender)
        {
            UpdateSliderLabels();

            SetIntegrationTimes();
        }

        partial void IntegrationLengthSliderChanged(NSSlider sender)
        {
            UpdateSliderLabels();

            SetIntegrationTimes();
        }

        partial void ToggleUseIntegrationFactor(NSButton sender)
        {
            Data.UseIntegrationFactorLength = !Data.UseIntegrationFactorLength;

            UpdateSliderLabels();

            SetIntegrationTimes();
        }

        partial void UseFactorToggled(NSObject sender)
        {
            Data.UseIntegrationFactorLength = !Data.UseIntegrationFactorLength;

            UpdateSliderLabels();

            SetIntegrationTimes();
        }

        float SliderToFactor()
        {
            return (float)Math.Pow(10, 2 * IntegrationLengthControl.FloatValue / IntegrationLengthControl.MaxValue);
        }

        float FactorToSlider(float value)
        {
            return (float)(Math.Log10(value) * IntegrationLengthControl.MaxValue / 2);
        }

        void SetIntegrationTimes()
        {
            if (Data.UseIntegrationFactorLength)
            {
                var factor = SliderToFactor();
                Data.SetCustomIntegrationTimes(IntegrationDelayControl.FloatValue, factor);
            }
            else Data.SetCustomIntegrationTimes(IntegrationDelayControl.FloatValue, IntegrationLengthControl.FloatValue);

            BaselineGraphView.Invalidate();
        }

        #endregion

        partial void ZoomSegControlClicked(NSSegmentedControl sender)
        {
            switch (sender.SelectedSegment)
            {
                case 0: BaselineGraphView.ShowAllVertical(); break;
                case 1: BaselineGraphView.ZoomBaseline(); break;
                case 2: BaselineGraphView.FocusPeak(); break;
                case 3: BaselineGraphView.UnfocusPeak();  break;
            }
        }

        partial void InjectionViewControlClicked(NSSegmentedControl sender)
        {
            switch (sender.SelectedSegment)
            {
                case 0: BaselineGraphView.SelectedPeak--; break;
                case 2: BaselineGraphView.SelectedPeak++; break;
            }

            sender.SetLabel((BaselineGraphView.SelectedPeak + 1).ToString(), 1);
        }

        partial void ScopeButtonClicked(NSObject sender)
        {
            BaselineGraphView.SetFeatureVisibility(ShowBaseline, ShowIntegrationRange, Corrected);
        }

        partial void DrawFeatureControlClicked(NSSegmentedControl sender)
        {
            BaselineGraphView.SetFeatureVisibility(DrawFeatureSegControl);
        }

        partial void ConfirmProcessingButtonClicked(NSObject sender)
        {
            
        }

        void UpdateProcessing()
        {
            Data.Processor.ProcessData();
        }

        private void OnSelectionChanged(object sender, ExperimentData e)
        {
            var current = DataManager.Current;

            BaselineGraphView.Initialize(current);

            BaselineGraphView.SetFeatureVisibility(ShowBaseline, ShowIntegrationRange, Corrected);

            UpdateUI();
        }

        private void OnInterpolationCompleted(object sender, EventArgs e)
        {
            if (Processor.BaselineCompleted) BaselineGraphView.Invalidate();

            //ConfirmProcessingButton.Enabled = DataManager.AllDataIsBaselineProcessed;
        }
    }
}
