// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Collections.Generic;
using DataReaders;
using AnalysisITC.AppClasses.AnalysisClasses.Models;
using AnalysisITC.GUI.MacOS.CustomViews;
using System.Linq;
using AnalysisITC.AppClasses.AnalysisClasses;

namespace AnalysisITC
{
	public partial class ExperimentDesignerViewController2 : NSViewController
	{
        private bool _isrunning = false;

        public static bool AutoRunExperimentSimulation { get; set; } = true;

        private ITCInstrument Instrument { get; set; } = ITCInstrument.MicroCalITC200;
        private ExperimentData Data { get; set; }
        private AnalysisModel Model { get; set; } = AnalysisModel.OneSetOfSites;
        private SingleModelFactory Factory { get; set; }
        private List<ParameterValueAdjustmentView> ParameterControls = new List<ParameterValueAdjustmentView>();
        private List<OptionAdjustmentView> OptionControls = new List<OptionAdjustmentView>();

        private const double DesignerTandemMixingFraction = 0.20;
        private const int DefaultTandemSegmentCount = 2;
        private const double MicroliterToLiter = 1.0 / 1000000.0;
        private const double LiterToMicroliter = 1000000.0;
        private const double DefaultManualInjectionVolumeMicroliters = 2.0;
        private double SmallInjectionVolume = 0.5 / 1000000.0;

        private double GetConcFieldValue(NSTextField field, double def = 0) => field.StringValue.Length > 0 ? field.DoubleValue / 1000000 : def / 1000000;
        private FloatWithError CellConcentration
        {
            get
            {
                var conc = GetConcFieldValue(CellConcField, 10);

                return new FloatWithError(conc, 0);
            }
        }
        private FloatWithError SyringeConcentration
        {
            get
            {
                var conc = GetConcFieldValue(SyringeConcField, 100);

                return new FloatWithError(conc, 0);
            }
        }
        private bool UseSmallFirstInjection => SmallInitialInjCheckmark.State == NSCellStateValue.On;
        private bool UseTandemExperiment => TandemExperimentControl?.State == NSCellStateValue.On;
        private int TandemSegmentCount => UseTandemExperiment ? Math.Max(TandemSegmentCountField?.IntValue ?? DefaultTandemSegmentCount, 2) : 1;
        private bool UseAutoInjectionVolume => AutoVolume?.State != NSCellStateValue.Off;
        private int InjectionCount => Math.Max(InjectionCountField?.IntValue ?? 2, 2);

        public ExperimentDesignerViewController2 (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            ModelMenu.RemoveAllItems();
            //InstrumentMenu.RemoveAllItems();

            foreach (var instrument in DataReaders.ITCInstrumentAttribute.GetITCInstruments())
            {
                InstrumentMenu.AddItem(new NSMenuItem(instrument.GetProperties().Name) { Tag = (int)instrument });
            }

            foreach (var type in AnalysisModelAttribute.GetAll())
            {
                ModelMenu.AddItem(new NSMenuItem(type.GetProperties().Name) { Tag = (int)type, Enabled = true });
            }

            InjectionCountField.Changed += InjectionCountField_Changed;
            InjectionCountStepper.Activated += InjectionCountStepper_Activated;
            SetupInjectionVolumeControlEvents();
            SetupTandemExperimentControlEvents();
            ModelControl.Enabled = false;

            SolverInterface.AnalysisStarted += SolverInterface_AnalysisStarted;
            SolverInterface.AnalysisFinished += SolverInterface_AnalysisFinished;
        }

        private void SetupInjectionVolumeControlEvents()
        {
            if (InjectionVolumeField != null)
                InjectionVolumeField.Changed += InjectionVolumeField_Changed;
            if (InjectionVolumeStepper != null)
                InjectionVolumeStepper.Activated += InjectionVolumeStepper_Activated;

            UpdateInjectionVolumeControls(InjectionCount);
        }

        private void SetupTandemExperimentControlEvents()
        {
            if (TandemSegmentCountField != null && TandemSegmentCountField.IntValue < 2)
                TandemSegmentCountField.IntValue = DefaultTandemSegmentCount;

            if (TandemSegmentCountStepper != null)
                TandemSegmentCountStepper.IntValue = TandemSegmentCountField?.IntValue ?? DefaultTandemSegmentCount;

            if (TandemExperimentControl != null)
                TandemExperimentControl.Activated += TandemExperimentControl_Activated;
            if (TandemSegmentCountField != null)
                TandemSegmentCountField.Changed += TandemSegmentCountField_Changed;
            if (TandemSegmentCountStepper != null)
                TandemSegmentCountStepper.Activated += TandemSegmentCountStepper_Activated;
        }

        private void TandemExperimentControl_Activated(object sender, EventArgs e)
        {
            SetupExperiment();
        }

        private void TandemSegmentCountField_Changed(object sender, EventArgs e)
        {
            if (TandemSegmentCountField == null || TandemSegmentCountStepper == null) return;

            var value = Math.Max(TandemSegmentCountField.IntValue, 2);
            TandemSegmentCountField.IntValue = value;
            TandemSegmentCountStepper.IntValue = value;

            SetupExperiment();
        }

        private void TandemSegmentCountStepper_Activated(object sender, EventArgs e)
        {
            if (TandemSegmentCountField == null || TandemSegmentCountStepper == null) return;

            TandemSegmentCountField.IntValue = TandemSegmentCountStepper.IntValue;

            SetupExperiment();
        }

        private void SolverInterface_AnalysisFinished(object sender, SolverConvergence e) { _isrunning = false; ApplyModelButton.Enabled = true; }
        private void SolverInterface_AnalysisStarted(object sender, TerminationFlag e) { _isrunning = true; ApplyModelButton.Enabled = false; }

        partial void SyringeCellAction(NSObject sender)
        {
            SetupExperiment();
        }

        partial void SimulateNoiseControlAction(NSObject sender)
        {
            SetupExperiment();
        }

        private void InjectionCountStepper_Activated(object sender, EventArgs e)
        {
            InjectionCountField.IntValue = InjectionCountStepper.IntValue;
            UpdateInjectionVolumeControls(InjectionCount);

            SetupExperiment();
        }

        private void InjectionCountField_Changed(object sender, EventArgs e)
        {
            InjectionCountStepper.IntValue = InjectionCountField.IntValue;
            UpdateInjectionVolumeControls(InjectionCount);

            SetupExperiment();
        }

        private void InjectionVolumeField_Changed(object sender, EventArgs e)
        {
            SyncManualInjectionVolumeFromField();

            SetupExperiment();
        }

        private void InjectionVolumeStepper_Activated(object sender, EventArgs e)
        {
            if (InjectionVolumeStepper == null) return;

            SetInjectionVolumeControlValues(InjectionVolumeStepper.DoubleValue);

            SetupExperiment();
        }

        partial void InjectionInputChanged(NSObject sender)
        {
            UpdateInjectionVolumeControls(InjectionCount);
            SetupExperiment();
        }

        partial void InstrumentControlAction(NSPopUpButton sender)
        {
            Instrument = (ITCInstrument)(int)sender.SelectedItem.Tag;

            var instrumentinfo = "";

            instrumentinfo += "Syringe volume:\t " + (1000000 * Instrument.GetProperties().StandardSyringeVolume).ToString("F1") + " µl" + Environment.NewLine;
            instrumentinfo += "Cell volume: \t " + (1000000 * Instrument.GetProperties().StandardCellVolume).ToString("F1") + " µl";

            InstrumentDescriptionField.StringValue = instrumentinfo;

            UpdateInjectionVolumeControls(InjectionCount);
            SetupExperiment();
        }

        partial void ModelControlAction(NSPopUpButton sender)
        {
            Model = (AnalysisModel)(int)sender.SelectedTag;

            SetupModel();
        }

        void SetupExperiment()
        {
            Data = new ExperimentData("ExperimentDesignerData");

            Data.Instrument = Instrument;

            Data.CellVolume = Instrument.GetProperties().StandardCellVolume;
            Data.CellConcentration = CellConcentration;
            Data.SyringeConcentration = SyringeConcentration;

            int injcount = InjectionCount;
            double volume = GetInjectionVolume(injcount);

            var segments = new List<TandemConcatenation.TandemInjectionSegment>();

            for (int segment = 0; segment < TandemSegmentCount; segment++)
            {
                var segmentStart = Data.Injections.Count;

                for (int i = 0; i < injcount; i++)
                {
                    var injectionID = Data.Injections.Count;

                    if (i == 0 && UseSmallFirstInjection)
                    {
                        Data.Injections.Add(new InjectionData(Data, injectionID, SmallInjectionVolume, 0, false));
                    }
                    else Data.Injections.Add(new InjectionData(Data, injectionID, volume, 0, true));
                }

                if (UseTandemExperiment)
                    segments.Add(new TandemConcatenation.TandemInjectionSegment(segmentStart, injcount, $"Load {segment + 1}"));
            }

            if (UseTandemExperiment)
                TandemConcatenation.ProcessInjectionsWithBackMixing(Data, segments, CreateDesignerTandemBackMixingSettings());
            else
                RawDataReader.ProcessInjections(Data);

            SetInjectionDescription();

            ModelControl.Enabled = true;

            SetupModel();
        }

        private double GetInjectionVolume(int injcount)
        {
            if (UseAutoInjectionVolume)
                return CalculateAutomaticInjectionVolume(injcount);

            return GetManualInjectionVolumeMicroliters() * MicroliterToLiter;
        }

        private double CalculateAutomaticInjectionVolume(int injcount)
        {
            var volume = UseSmallFirstInjection ?
                (Instrument.GetProperties().StandardSyringeVolume - SmallInjectionVolume) / (injcount - 1) :
                Instrument.GetProperties().StandardSyringeVolume / injcount;

            return Math.Floor(volume * 10000000) / 10000000;
        }

        private void UpdateInjectionVolumeControls(int injcount)
        {
            var auto = UseAutoInjectionVolume;

            if (auto)
                SetInjectionVolumeControlValues(CalculateAutomaticInjectionVolume(injcount) * LiterToMicroliter);
            else
                SyncManualInjectionVolumeFromField();

            if (InjectionVolumeField != null)
                InjectionVolumeField.Enabled = !auto;
            if (InjectionVolumeStepper != null)
                InjectionVolumeStepper.Enabled = !auto;
        }

        private void SyncManualInjectionVolumeFromField()
        {
            if (InjectionVolumeField == null) return;

            SetInjectionVolumeControlValues(InjectionVolumeField.DoubleValue);
        }

        private double GetManualInjectionVolumeMicroliters()
        {
            return ValidateInjectionVolumeMicroliters(InjectionVolumeField?.DoubleValue ?? DefaultManualInjectionVolumeMicroliters);
        }

        private void SetInjectionVolumeControlValues(double volumeMicroliters)
        {
            var value = ValidateInjectionVolumeMicroliters(volumeMicroliters);

            if (InjectionVolumeField != null)
                InjectionVolumeField.DoubleValue = value;
            if (InjectionVolumeStepper != null)
                InjectionVolumeStepper.DoubleValue = value;
        }

        private double ValidateInjectionVolumeMicroliters(double volumeMicroliters)
        {
            var min = InjectionVolumeStepper?.MinValue ?? 0.1;
            var max = InjectionVolumeStepper?.MaxValue ?? 20.0;
            var value = volumeMicroliters > 0 ? volumeMicroliters : DefaultManualInjectionVolumeMicroliters;

            return Math.Min(Math.Max(value, min), max);
        }

        private TandemConcatenation.BackMixingSettings CreateDesignerTandemBackMixingSettings()
        {
            return new TandemConcatenation.BackMixingSettings
            {
                UseBackMixingMethod = true,
                DidRemoveOverflow = true,
                DeadVolume = Instrument.GetProperties().DeadVolume,
                MixingFraction = DesignerTandemMixingFraction,
                RemoveOverflowVolume = 0.0,
            };
        }

        private void SetInjectionDescription()
        {
            string injdescription = "";

            for (int i = 0; i < Data.Injections.Count; i++)
            {
                var curr = Data.Injections[i];
                var next = i < Data.InjectionCount - 1 ? Data.Injections[i + 1] : null;
                var prev = i > 0 ? Data.Injections[i - 1] : null;

                if (Data.Injections.Where(inj => inj.ID > i).All(inj => inj.Volume == curr.Volume))
                {
                    // All subsequent are identical, finish up
                    injdescription += "#" + (i + 1).ToString() + "-" + Data.Injections.Count.ToString() + ": " + (1000000 * curr.Volume).ToString("F1") + " µl, ";
                    break;
                }
                else if (next != null && curr.Volume == next.Volume)
                {
                    string row = $"#{i + 1}-";

                    while (i < Data.InjectionCount)
                    {
                        i++;

                        next = i < Data.InjectionCount - 1 ? Data.Injections[i + 1] : null;

                        if (next == null || curr.Volume != next.Volume) break;
                    }

                    row += $"{i + 1}: {1000000 * curr.Volume:F1} µl, ";

                    injdescription += row;
                }
                else if (next != null && curr.Volume != next.Volume)
                    injdescription += "#" + (i + 1).ToString() + ": " + (1000000 * curr.Volume).ToString("F1") + " µl, ";
                else if (prev != null && curr.Volume != prev.Volume)
                    injdescription += "#" + (i + 1).ToString() + ": " + (1000000 * curr.Volume).ToString("F1") + " µl, ";
            }

            injdescription = injdescription.Substring(0, injdescription.Length - 2);

            InjectionInfoField.StringValue = injdescription;
        }

        void SetupModel()
        {
            if (Data == null) return;
            Factory = new SingleModelFactory(Model);

            Factory.InitializeModel(Data);

            if (Factory == null) return;

            ClearStackView(ModelOptionsStackView);
            ClearStackView(ParameterStackView);

            ParameterValueAdjustmentView[] tmppars = new ParameterValueAdjustmentView[ParameterControls.Count];

            ParameterControls.CopyTo(tmppars);
            ParameterControls.Clear();

            foreach (var par in Factory.GetExposedParameters())
            {
                ParameterValueAdjustmentView sv;

                // Set some meaningful default value for enthalpy type variables
                if (par.Key.GetProperties().ParentType == ParameterType.Enthalpy1)
                    par.Update(-30000);
                if (par.Key.GetProperties().ParentType == ParameterType.Nvalue1) par.Update(1);

                if (tmppars.ToList().Exists(view => view.Key == par.Key))
                {
                    sv = tmppars.ToList().Find(view => view.Key == par.Key);
                }
                else
                {
                    sv = new ParameterValueAdjustmentView(
                        new CoreGraphics.CGRect(0, 0, ParameterStackView.Frame.Width, 20),
                        par,
                        AdjustmentViewMode.Designer);
                }
                sv.ValueChanged -= ParameterControl_ValueChanged;
                sv.ValueChanged += ParameterControl_ValueChanged;
                ParameterControls.Add(sv);

                ParameterStackView.AddArrangedSubview(sv);
            }

            foreach (var sv in OptionControls)
            {
                sv.ApplyOptions();
            }

            var tmpopts = OptionControls.ToArray();
            OptionControls.Clear();

            bool showoptions = Factory.Model.ModelOptions.Count > 0;
            ModelOptionsStackView.Hidden = !showoptions;
            ModelOptionsLine.Hidden = !showoptions;
            ModelOptionsLabel.Hidden = !showoptions;

            if (showoptions)
            {
                foreach (var opt in Factory.GetExposedModelOptions())
                {
                    var old = tmpopts.FirstOrDefault(v => v.Key == opt.Key);
                    if (old != null)
                    {
                        opt.Value.BoolValue = old.Option.BoolValue;
                        opt.Value.ParameterValue = old.Option.ParameterValue;
                        opt.Value.IntValue = old.Option.IntValue;
                        opt.Value.DoubleValue = old.Option.DoubleValue;
                        opt.Value.StringValue = old.Option.StringValue;
                    }

                    var sv = new OptionAdjustmentView(
                        new CoreGraphics.CGRect(0, 0, ModelOptionsStackView.Frame.Width, 20),
                        opt.Value,
                        AdjustmentViewMode.Designer);

                    sv.SetupDesignerLayout();
                    sv.ValueChanged -= OptionControl_ValueChanged;
                    sv.ValueChanged += OptionControl_ValueChanged;
                    OptionControls.Add(sv);
                    ModelOptionsStackView.AddArrangedSubview(sv);
                }
            }

            RefreshDesignerControlStates();

            if (AutoRunExperimentSimulation)
                UpdateSyntheticData();
        }

        private static void ClearStackView(NSStackView stack)
        {
            foreach (var view in stack.ArrangedSubviews.ToArray())
            {
                stack.RemoveArrangedSubview(view);
                view.RemoveFromSuperview();
            }
        }

        partial void ApplyModelSettings(NSButton sender)
        {
            UpdateSyntheticData();
            FitSyntheticData();
        }

        private void ParameterControl_ValueChanged(object sender, EventArgs e)
        {
            if (AutoRunExperimentSimulation)
                UpdateSyntheticData();
        }

        private void OptionControl_ValueChanged(object sender, EventArgs e)
        {
            if (AutoRunExperimentSimulation)
                UpdateSyntheticData();
            else
                ApplyDesignerInputsToFactory();

            RefreshDesignerControlStates();
        }

        private void RefreshDesignerControlStates()
        {
            if (Factory == null) return;

            var attributes = Factory.GetExposedModelOptions();

            foreach (var sv in OptionControls)
                sv.UpdateState(attributes);

            foreach (var sv in ParameterControls)
                sv.UpdateState(attributes);
        }

        private void UpdateSyntheticData()
        {
            if (_isrunning || Factory == null) return;

            ApplyDesignerInputsToFactory();
            Factory.BuildModel();
            SimulateSyntheticData();
        }

        private void ApplyDesignerInputsToFactory()
        {
            if (Factory == null) return;

            foreach (var sv in ParameterControls)
            {
                Factory.UpdateParameter(sv.Key, sv.Value, false);
            }

            foreach (var sv in OptionControls)
            {
                sv.ApplyOptions();
            }
        }

        private void SimulateSyntheticData()
        {
            if (Data?.Model == null) return;

            Data.Model.Solution = SolutionInterface.FromModel(Data.Model, SolverConvergence.ReportStopped(DateTime.Now));

            foreach (var inj in Data.Injections)
            {
                var injmass = IsSmallInitialInjection(inj) ? inj.InjectionMass * 0.8 : inj.InjectionMass;
                var dH = Data.Model.EvaluateEnthalpy(inj.ID);
                var noise = SimulateNoiseControl.State == NSCellStateValue.On ?
                    2000 / (Math.Sqrt(inj.InjectionMass * Math.Pow(10, 11))) :
                    0;
                var heat = injmass * new FloatWithError(dH, noise).Sample();
                inj.SetPeakArea(new(heat));
            }

            SimGraphView.Initialize(Data);
        }

        private bool IsSmallInitialInjection(InjectionData injection)
        {
            if (!UseSmallFirstInjection) return false;

            if (Data?.Segments != null)
                return Data.Segments.Any(segment => segment.FirstInjectionID == injection.ID);

            return injection.ID == 0;
        }

        private void FitSyntheticData()
        {
            if (_isrunning || Factory == null || Data?.Model == null) return;

            var solver = Solver.Initialize(Factory);
            solver.CanCreateAnalysisResult = false;
            solver.SolverToleranceModifier = 2;
            solver.ErrorEstimationMethod = SimulateNoiseControl.State == NSCellStateValue.On ? ErrorEstimationMethod.BootstrapResiduals : ErrorEstimationMethod.None;
            solver.BootstrapIterations = 50;
            var mco = (solver as Solver).Model.ModelCloneOptions;
            mco.IncludeConcentrationErrorsInBootstrap = true;
            mco.EnableAutoConcentrationVariance = false;

            solver.Analyze();
        }
    }
}
