// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Collections.Generic;
using static AnalysisITC.TandemConcatenation;
using System.Linq;
using System.Threading.Tasks;

namespace AnalysisITC
{
	public partial class ExperimentMergerViewController : NSViewController
	{
        BackMixingSettings MergeSettings { get; set; }

        ExperimentMergeQueueDataSource mergeSource;
        ExperimentMergeQueueDelegate mergeDelegate;
        Dictionary<NSControl, bool> ToolControlEnabledStates;
        bool IsCreatingMergedExperiment;

        bool IsAutoBackMixingEnabled =>
            MergeSettings.UseBackMixingMethod
            && AutoBackMixingControl.State == NSCellStateValue.On;

        public ExperimentMergerViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            StatusBarManager.SetStatus(StateManager.ProgramSubStateString(ProgramSubState.MergeTool), -1);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            MergeSettings = new BackMixingSettings();

            mergeSource = new ExperimentMergeQueueDataSource();
            mergeSource.SetFromOpenExperiments(defaultActiveFromInclude: false); // uses DataManager.Data / Include :contentReference[oaicite:5]{index=5}

            mergeDelegate = new ExperimentMergeQueueDelegate(mergeSource);
            mergeDelegate.QueueChanged += (_, __) =>
            {
                var ids = CaptureSelectedIDs(MergeTableView, mergeSource);
                MergeTableView.ReloadData();
                RestoreSelectedIDs(MergeTableView, mergeSource, ids);

                ValidateMergeButton();
            };
            mergeDelegate.SelectionChanged += (_, __) =>
            {
                ValidateMergeButton();
            };

            MergeTableView.DataSource = mergeSource;
            MergeTableView.Delegate = mergeDelegate;
            if (MergeTableView is ToggleSelectTableView toggleSelectTableView)
                toggleSelectTableView.MoveSelectedRowsRequested += (_, offset) =>
                    mergeDelegate.MoveSelectedRows(MergeTableView, offset);

            MergeTableView.ReloadData();

            SetMixingSliderValue(MergeSettings.MixingFraction);
            DeadVolumeTextField.DoubleValue = 1000000 * GetFirstSelectedExperimentOrDefault().Instrument.GetProperties().DeadVolume;
            SetupMethodControls();

            ValidateMergeButton();
        }

        void SetupMethodControls()
        {
            AutoBackMixingControl.Enabled = MergeSettings.UseBackMixingMethod;
            DeadVolumeTextField.Enabled = MergeSettings.UseBackMixingMethod;
            BackMixingSliderControl.Enabled = MergeSettings.UseBackMixingMethod && !IsAutoBackMixingEnabled;
            RemovedTitratedAfterExperimentControl.Enabled = MergeSettings.UseBackMixingMethod;
            BackMixFracLabel.TextColor = BackMixingSliderControl.Enabled ? NSColor.Label : NSColor.TertiaryLabel;
            BackMixLabel.TextColor = MergeSettings.UseBackMixingMethod ? NSColor.Label : NSColor.TertiaryLabel;
            DeadVolLabel.TextColor = MergeSettings.UseBackMixingMethod ? NSColor.Label : NSColor.TertiaryLabel;

            ValidateMergeButton();
        }

        void SetMixingSliderValue(double value)
        {
            BackMixingSliderControl.DoubleValue = Math.Clamp(value, 0, 1.0);
            BackMixingSliderControl.SendAction(BackMixingSliderControl.Action, BackMixingSliderControl.Target);
        }

        void ValidateMergeButton()
        {
            var n = mergeDelegate.GetSelectedExperiments(MergeTableView).Count;

            MergeButtonControl.Enabled = !IsCreatingMergedExperiment
                && n > 1
                && (!IsAutoBackMixingEnabled || n <= 3);
        }

        void SetToolInteractionEnabled(bool enabled)
        {
            if (!enabled)
            {
                ToolControlEnabledStates = FindControls(View)
                    .ToDictionary(control => control, control => control.Enabled);

                foreach (var control in ToolControlEnabledStates.Keys)
                    control.Enabled = false;

                return;
            }

            if (ToolControlEnabledStates == null) return;

            foreach (var state in ToolControlEnabledStates)
                state.Key.Enabled = state.Value;

            ToolControlEnabledStates = null;
        }

        IEnumerable<NSControl> FindControls(NSView view)
        {
            foreach (var subview in view.Subviews)
            {
                if (subview is NSControl control) yield return control;

                foreach (var nestedControl in FindControls(subview))
                    yield return nestedControl;
            }
        }

        ExperimentData GetFirstSelectedExperimentOrDefault()
        {
            var exps = mergeDelegate.GetSelectedExperiments(MergeTableView);

            if (exps.Count == 0)
            {
                exps.Add(mergeSource.Items.First().Data);
            }

            return exps[0];
        }

        HashSet<string> CaptureSelectedIDs(NSTableView tableView, ExperimentMergeQueueDataSource source)
        {
            var ids = new HashSet<string>();
            var idx = tableView.SelectedRows;

            idx.EnumerateIndexes((nuint i, ref bool stop) =>
            {
                if (i < (nuint)source.Items.Count)
                    ids.Add(source.Items[(int)i].UniqueID);
            });

            return ids;
        }

        void RestoreSelectedIDs(NSTableView tableView, ExperimentMergeQueueDataSource source, HashSet<string> ids)
        {
            var newIdx = new NSMutableIndexSet();
            for (int i = 0; i < source.Items.Count; i++)
                if (ids.Contains(source.Items[i].UniqueID))
                    newIdx.Add((nuint)i);

            tableView.SelectRows(newIdx, byExtendingSelection: false);
        }

        partial void MergeMethodControlAction(NSSegmentedControl sender)
        {
            MergeSettings.UseBackMixingMethod = sender.SelectedSegment == 1;

            SetupMethodControls();
        }

        partial void AutoBackMixingControlAction(NSObject sender)
        {
            SetupMethodControls();
        }

        async partial void CreateNewMergedExperimentAction(NSObject sender)
        {
            MergeSettings.DeadVolume = DeadVolumeTextField.FloatValue * 1e-6;
            MergeSettings.MixingFraction = BackMixingSliderControl.FloatValue;
            MergeSettings.DidRemoveOverflow = RemovedTitratedAfterExperimentControl.State == NSCellStateValue.On;

            var exps = mergeDelegate.GetSelectedExperiments(MergeTableView);
            var autoBackMixingEnabled = IsAutoBackMixingEnabled;

            IsCreatingMergedExperiment = true;
            if (autoBackMixingEnabled) SetToolInteractionEnabled(false);
            ValidateMergeButton();

            try
            {
                ExperimentData mergeddata;
                if (autoBackMixingEnabled)
                {
                    StatusBarManager.SetStatus("Scanning tandem back-mixing degrees...", 0, priority: 1);
                    StatusBarManager.SetSecondaryStatus("", 0);
                    StatusBarManager.SetProgress(0);

                    var bestPoint = await Task.Run(() => TandemMixingScanner.FindBestAdaptive(
                        exps,
                        MergeSettings.Copy(),
                        (completed, total) => NSApplication.SharedApplication.BeginInvokeOnMainThread(() =>
                        {
                            StatusBarManager.SetProgress(completed / (double)total);
                            StatusBarManager.SetSecondaryStatus($"{completed}/{total}", 0);
                        })));
                    if (bestPoint == null)
                        throw new InvalidOperationException("The tandem back-mixing scan did not produce a valid fit.");

                    StatusBarManager.SetStatus("Creating merged experiment...", 0, priority: 1);
                    StatusBarManager.SetSecondaryStatus("", 0);
                    StatusBarManager.SetProgress(1);
                    mergeddata = TandemConcatenation.ConcatTandemWithBackMixing(
                        exps,
                        MergeSettings,
                        bestPoint.TransitionMixingFractions);
                }
                else if (MergeSettings.UseBackMixingMethod)
                {
                    mergeddata = TandemConcatenation.ConcatTandemWithBackMixing(exps, MergeSettings);
                }
                else
                {
                    mergeddata = TandemConcatenation.ConcatTandem(exps);
                }

                await mergeddata.Processor.ProcessData();
                DataManager.AddData(mergeddata);

                DismissViewController(this);
            }
            finally
            {
                IsCreatingMergedExperiment = false;
                if (autoBackMixingEnabled)
                {
                    SetToolInteractionEnabled(true);
                    SetupMethodControls();
                }
                else
                {
                    ValidateMergeButton();
                }
            }
        }

        public override void ViewWillDisappear()
        {
            base.ViewWillDisappear();

            StatusBarManager.ClearAppStatus();
        }
    }
}
