// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Collections.Generic;
using DataReaders;
using AnalysisITC.AppClasses.AnalysisClasses.Models;
using AnalysisITC.GUI.MacOS.CustomViews;
using System.Linq;
using AnalysisITC.AppClasses.AnalysisClasses;

namespace AnalysisITC
{
	public partial class ExperimentDesignerViewController2 : NSViewController
	{
        public static bool AutoRunExperimentSimulation { get; set; } = false;

        private ITCInstrument Instrument { get; set; } = ITCInstrument.MicroCalITC200;
        private ExperimentData Data { get; set; }
        private AnalysisModel Model { get; set; } = AnalysisModel.OneSetOfSites;
        private SingleModelFactory Factory { get; set; }
        private List<ParameterValueAdjustmentView> ParameterControls = new List<ParameterValueAdjustmentView>();
        private List<OptionAdjustmentView> OptionControls = new List<OptionAdjustmentView>();

        private double SmallInjectionVolume = 0.5 / 1000000.0;

        private double GetConcFieldValue(NSTextField field, double def = 0) => field.StringValue.Length > 0 ? field.DoubleValue / 1000000 : def / 1000000;
        private FloatWithError CellConcentration
        {
            get
            {
                var conc = GetConcFieldValue(CellConcField, 10);
                var error = GetConcFieldValue(CellConcErrorField);

                return new FloatWithError(conc, error);
            }
        }
        private FloatWithError SyringeConcentration
        {
            get
            {
                var conc = GetConcFieldValue(SyringeConcField, 100);
                var error = GetConcFieldValue(SyringeConcErrorField);

                return new FloatWithError(conc, error);
            }
        }
        private bool UseSmallFirstInjection => SmallInitialInjCheckmark.State == NSCellStateValue.On;

        public ExperimentDesignerViewController2 (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            ModelMenu.RemoveAllItems();
            InstrumentMenu.RemoveAllItems();

            foreach (var instrument in DataReaders.ITCInstrumentAttribute.GetITCInstruments())
            {
                InstrumentMenu.AddItem(new NSMenuItem(instrument.GetProperties().Name) { Tag = (int)instrument });
            }

            foreach (var type in AnalysisModelAttribute.GetAll())
            {
                ModelMenu.AddItem(new NSMenuItem(type.GetProperties().Name) { Tag = (int)type, Enabled = true });
            }

            InjectionCountField.Changed += InjectionCountField_Changed;
            InjectionCountStepper.Activated += InjectionCountStepper_Activated;
            ModelControl.Enabled = false;

            SolverInterface.AnalysisStarted += SolverInterface_AnalysisStarted;
            SolverInterface.AnalysisFinished += SolverInterface_AnalysisFinished;
        }

        private void SolverInterface_AnalysisFinished(object sender, SolverConvergence e) => ApplyModelButton.Enabled = true;
        private void SolverInterface_AnalysisStarted(object sender, TerminationFlag e) => ApplyModelButton.Enabled = false;

        partial void SyringeCellAction(NSObject sender)
        {
            SetupExperiment();
        }

        partial void SimulateNoiseControlAction(NSObject sender)
        {
            SetupExperiment();
        }

        private void InjectionCountStepper_Activated(object sender, EventArgs e)
        {
            InjectionCountField.IntValue = InjectionCountStepper.IntValue;

            SetupExperiment();
        }

        private void InjectionCountField_Changed(object sender, EventArgs e)
        {
            InjectionCountStepper.IntValue = InjectionCountField.IntValue;

            SetupExperiment();
        }

        partial void InjectionInputChanged(NSObject sender)
        {
            SetupExperiment();
        }

        partial void InstrumentControlAction(NSPopUpButton sender)
        {
            Instrument = (DataReaders.ITCInstrument)(int)sender.SelectedItem.Tag;

            var instrumentinfo = "";

            instrumentinfo += "Syringe volume:\t " + (1000000 * Instrument.GetProperties().StandardSyringeVolume).ToString("F1") + " µl" + Environment.NewLine;
            instrumentinfo += "Cell volume: \t " + (1000000 * Instrument.GetProperties().StandardCellVolume).ToString("F1") + " µl";

            InstrumentDescriptionField.StringValue = instrumentinfo;

            SetupExperiment();
        }

        partial void ModelControlAction(NSPopUpButton sender)
        {
            Model = (AnalysisModel)(int)sender.SelectedTag;

            SetupModel();
        }

        void SetupExperiment()
        {
            Data = new ExperimentData("ExperimentDesignerData");

            Data.Instrument = Instrument;

            Data.CellVolume = Instrument.GetProperties().StandardCellVolume;
            Data.CellConcentration = CellConcentration;
            Data.SyringeConcentration = SyringeConcentration;

            int injcount = Math.Max(InjectionCountField.IntValue, 2);

            double volume = UseSmallFirstInjection ?
                (Instrument.GetProperties().StandardSyringeVolume - SmallInjectionVolume) / (injcount - 1) :
                (Instrument.GetProperties().StandardSyringeVolume) / (injcount);

            volume = Math.Floor(volume * 10000000) / 10000000;

            for (int i = 0; i < injcount; i++)
            {
                if (i == 0 && UseSmallFirstInjection)
                {
                    Data.Injections.Add(new InjectionData(Data, i, SmallInjectionVolume, 0, false));
                }
                else Data.Injections.Add(new InjectionData(Data, i, volume, 0, true));
            }

            RawDataReader.ProcessInjections(Data);

            SetInjectionDescription();

            ModelControl.Enabled = true;

            SetupModel();
        }

        private void SetInjectionDescription()
        {
            string injdescription = "";

            for (int i = 0; i < Data.Injections.Count; i++)
            {
                var curr = Data.Injections[i];
                var next = i < Data.InjectionCount - 1 ? Data.Injections[i + 1] : null;
                var prev = i > 0 ? Data.Injections[i - 1] : null;

                if (Data.Injections.Where(inj => inj.ID > i).All(inj => inj.Volume == curr.Volume))
                {
                    injdescription += "#" + (i + 1).ToString() + "-" + Data.Injections.Count.ToString() + ": " + (1000000 * curr.Volume).ToString("F1") + " µl, ";
                    break;
                }
                else if (next != null && curr.Volume != next.Volume)
                    injdescription += "#" + (i + 1).ToString() + ": " + (1000000 * curr.Volume).ToString("F1") + " µl, ";
                else if (prev != null && curr.Volume != prev.Volume)
                    injdescription += "#" + (i + 1).ToString() + ": " + (1000000 * curr.Volume).ToString("F1") + " µl, ";
            }

            injdescription = injdescription.Substring(0, injdescription.Length - 2);

            InjectionInfoField.StringValue = injdescription;
        }

        void SetupModel()
        {
            if (Data == null) return;
            Factory = new SingleModelFactory(Model);

            Factory.InitializeModel(Data);

            if (Factory == null) return;

            ClearStackView(ModelOptionsStackView);
            ClearStackView(ParameterStackView);

            ParameterValueAdjustmentView[] tmppars = new ParameterValueAdjustmentView[ParameterControls.Count];

            ParameterControls.CopyTo(tmppars);
            ParameterControls.Clear();

            foreach (var par in Factory.GetExposedParameters())
            {
                ParameterValueAdjustmentView sv;

                // Set some meaningful default value for enthalpy type variables
                if (par.Key.GetProperties().ParentType == ParameterType.Enthalpy1)
                    par.Update(-30000);

                if (tmppars.ToList().Exists(view => view.Key == par.Key))
                {
                    sv = tmppars.ToList().Find(view => view.Key == par.Key);
                }
                else
                {
                    sv = new ParameterValueAdjustmentView(new CoreGraphics.CGRect(0, 0, ParameterStackView.Frame.Width, 20), par, enablelock: false);
                }
                ParameterControls.Add(sv);

                ParameterStackView.AddArrangedSubview(sv);
            }

            foreach (var sv in OptionControls)
            {
                sv.ApplyOptions();
            }

            var tmpopts = OptionControls.ToArray();
            OptionControls.Clear();

            bool showoptions = Factory.Model.ModelOptions.Count > 0;
            ModelOptionsStackView.Hidden = !showoptions;
            ModelOptionsLine.Hidden = !showoptions;
            ModelOptionsLabel.Hidden = !showoptions;

            if (showoptions)
            {
                foreach (var opt in Factory.GetExposedModelOptions())
                {
                    var old = tmpopts.FirstOrDefault(v => v.Key == opt.Key);
                    if (old != null)
                    {
                        opt.Value.BoolValue = old.Option.BoolValue;
                        opt.Value.ParameterValue = old.Option.ParameterValue;
                        opt.Value.IntValue = old.Option.IntValue;
                        opt.Value.DoubleValue = old.Option.DoubleValue;
                        opt.Value.StringValue = old.Option.StringValue;
                    }

                    var sv = new OptionAdjustmentView(
                        new CoreGraphics.CGRect(0, 0, ModelOptionsStackView.Frame.Width, 20),
                        opt.Value);

                    sv.SetupDesignerLayout();
                    OptionControls.Add(sv);
                    ModelOptionsStackView.AddArrangedSubview(sv);
                }
            }

            UpdateWindowHeightToFitContent();

            if (AutoRunExperimentSimulation)
                ApplyModelSettings(null);
        }

        private static void ClearStackView(NSStackView stack)
        {
            foreach (var view in stack.ArrangedSubviews.ToArray())
            {
                stack.RemoveArrangedSubview(view);
                view.RemoveFromSuperview();
            }
        }

        private void UpdateWindowHeightToFitContent(bool animate = false)
        {
            var window = View.Window;
            if (window == null) return;

            View.NeedsLayout = true;
            View.LayoutSubtreeIfNeeded();

            var fitting = View.FittingSize;
            var frame = window.Frame;
            var contentRect = window.ContentRectFor(frame);

            var targetHeight = fitting.Height;
            var deltaHeight = targetHeight - contentRect.Height;

            if (Math.Abs(deltaHeight) < 1) return;

            frame.Y -= deltaHeight;      // keep top edge fixed
            frame.Height += deltaHeight;

            window.SetFrame(frame, true, animate);
        }

        partial void ApplyModelSettings(NSButton sender)
        {
            if (Factory == null) return;

            foreach (var sv in ParameterControls)
            {
                Factory.UpdateParameter(sv.Key, sv.Value, false);
            }

            foreach (var sv in OptionControls)
            {
                sv.ApplyOptions();
            }

            Factory.BuildModel();

            Data.Model.Solution = SolutionInterface.FromModel(Data.Model, SolverConvergence.ReportStopped(DateTime.Now));

            foreach (var inj in Data.Injections)
            {
                var injmass = inj.ID == 0 && UseSmallFirstInjection ? inj.InjectionMass * 0.8 : inj.InjectionMass;
                var dH = Data.Model.EvaluateEnthalpy(inj.ID);
                var noise = SimulateNoiseControl.State == NSCellStateValue.On ?
                    2000 / (Math.Sqrt(inj.InjectionMass * Math.Pow(10, 11))) :
                    0;
                var heat = injmass * new FloatWithError(dH, noise).Sample();
                inj.SetPeakArea(new(heat));
            }

            SimGraphView.Initialize(Data);

            var solver = Solver.Initialize(Factory);
            solver.SolverToleranceModifier = 2;
            solver.ErrorEstimationMethod = SimulateNoiseControl.State == NSCellStateValue.On ? ErrorEstimationMethod.BootstrapResiduals : ErrorEstimationMethod.None;
            solver.BootstrapIterations = 50;
            var mco = (solver as Solver).Model.ModelCloneOptions;
            mco.IncludeConcentrationErrorsInBootstrap = true;
            mco.EnableAutoConcentrationVariance = false;

            solver.Analyze();
        }
    }
}