// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class PreferencesViewController : NSViewController
	{
		public PreferencesViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            RefTempField.StringValue = AppSettings.ReferenceTemperature.ToString("F2");
            MinTempSpanSlider.DoubleValue = AppSettings.MinimumTemperatureSpanForFitting;
            TempSpanLabel.DoubleValue = AppSettings.MinimumTemperatureSpanForFitting;
            DefaultErrorMethodControl.SelectedSegment = (int)AppSettings.DefaultErrorEstimationMethod;
            IncludeConcVarianceCheck.State = AppSettings.IncludeConcentrationErrorsInBootstrap ? NSCellStateValue.On : NSCellStateValue.Off;
            DefaultBootstrapIterationSlider.DoubleValue = Math.Log10(AppSettings.DefaultBootstrapIterations);

            FuncToleranceSlider.DoubleValue = AppSettings.OptimizerTolerance;

            SetFuncToleranceLabel(AppSettings.OptimizerTolerance);
        }

        partial void DefaultBootstrapIterationAction(NSSlider sender)
        {
            DefaultBootstrapIterationLabel.StringValue = ((int)Math.Pow(10, DefaultBootstrapIterationSlider.DoubleValue)).ToString();
        }

        partial void FuncToleranceAction(NSSlider sender)
        {
            SetFuncToleranceLabel(sender.DoubleValue);
        }

        partial void Apply(NSObject sender)
        {
            if (double.TryParse(RefTempField.StringValue, out var val))
            {
                AppSettings.ReferenceTemperature = val;
            }

            AppSettings.MinimumTemperatureSpanForFitting = MinTempSpanSlider.DoubleValue;

            //Fitting
            AppSettings.DefaultErrorEstimationMethod = (ErrorEstimationMethod)(int)DefaultErrorMethodControl.SelectedSegment;
            AppSettings.IncludeConcentrationErrorsInBootstrap = IncludeConcVarianceCheck.State == NSCellStateValue.On;
            AppSettings.DefaultBootstrapIterations = (int)Math.Pow(10, DefaultBootstrapIterationSlider.DoubleValue);

            this.DismissViewController(this);
        }

        partial void Close(NSObject sender)
        {
            this.DismissViewController(this);
        }

        void SetFuncToleranceLabel(double value)
        {
            if (value < double.Epsilon) value = double.Epsilon;
            FuncToleranceLabel.DoubleValue = value;
        }
    }
}
