// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
    public partial class SideBarViewController : NSViewController
    {
        public static NSImage DataNotProcessedImage { get; private set; } = null;
        public static NSImage DataDisabledImage { get; private set; } = null;
        public static NSImage DataEnabledImage { get; private set; } = null;

        ExperimentDataDelegate _tableDelegate;
        int? _pendingRemovedRow;
        AnalysisITCDataSource _pendingRemovalSource;
        int _pendingRemovalRowsBefore = -1;
        bool _pendingRemovalModelUpdateObserved;
        bool _suppressTableSelectionCallback;

        #region Constructors

        // Called when created from unmanaged code
        public SideBarViewController(IntPtr handle) : base(handle)
        {
            Initialize();
        }

        // Called when created directly from a XIB file
        [Export("initWithCoder:")]
        public SideBarViewController(NSCoder coder) : base(coder)
        {
            Initialize();
        }

        // Call to load from the XIB/NIB file
        public SideBarViewController() : base("DataSeriesSideBarView", NSBundle.MainBundle)
        {
            Initialize();
        }

        // Shared initialization code
        void Initialize()
        {
            DataManager.DataDidChange += OnDataManagerUpdated;
            DataManager.SelectionDidChange += DataManager_SelectionDidChange;
            DataManager.AnalysisResultSelected += DataManager_AnalysisResultSelected;
            DataManager.RemoveListIndices += DataManager_RemoveListIndices;
            DataManager.UpdateTable += ExperimentDetailsPopoverController_UpdateTable;

            ExperimentDataViewCell.ExpandDataButtonClicked += ExperimentDataViewCell_ShowDetails;
            AnalysisResultView.ExpandDataButtonClicked += AnalysisResultView_ExpandDataButtonClicked;

            ExperimentDetailsPopoverController.UpdateTable += ExperimentDetailsPopoverController_UpdateTable;
            BindingAnalysisViewController.UpdateTable += ExperimentDetailsPopoverController_UpdateTable;
            ViewController.UpdateTable += ExperimentDetailsPopoverController_UpdateTable;
            ViewController.WillRemoveData += OnRowWillRemoveEvent;
            ViewController.RemoveData += OnRowRemoveEvent;

            AnalysisITCDataSource.SourceWasSorted += AnalysisITCDataSource_SourceWasSorted;
            AppSettings.SettingsDidUpdate += AppSettings_SettingsDidUpdate;
        }

        string DescribeItem(ITCDataContainer item)
        {
            if (item == null) return "<null>";

            var name = string.IsNullOrWhiteSpace(item.Name) ? item.FileName : item.Name;
            return $"{item.GetType().Name}[Name='{name}', ID='{item.UniqueID}']";
        }

        private void AnalysisITCDataSource_SourceWasSorted(object sender, EventArgs e)
        {
            var item = DataManager.Source.SelectedItem;
            AppEventHandler.PrintAndLog(
                $"SideBar.SourceWasSorted: selectedBefore={DescribeItem(item)}, rows={DataManager.Source?.Content?.Count ?? -1}");

            ReloadTable();

            DataManager.SelectIndex(DataManager.Source.Content.IndexOf(item));
        }

        private void ExperimentDetailsPopoverController_UpdateTable(object sender, EventArgs e)
        {
            int idx = DataManager.Source.SelectedIndex;
            AppEventHandler.PrintAndLog(
                $"SideBar.UpdateTable event: selectedIndex={idx}, rows={DataManager.Source?.Content?.Count ?? -1}, sender={sender?.GetType().Name ?? "<null>"}",
                1);

            ReloadTable();

            DataManager.SelectIndex(idx);
        }

        private void AppSettings_SettingsDidUpdate(object sender, EventArgs e)
        {
            ReloadTable();
        }

        private void ExperimentDataViewCell_ShowDetails(object sender, ExperimentData e)
        {
            ExperimentDetailsPopoverController.Data = e;

            try
            {
                DataManager.SelectIndex(DataManager.SourceItems.IndexOf(e));
            }
            catch
            {
                AppEventHandler.PrintAndLog("Failed to select detail view experiment...");
            }

            PerformSegue("DetailsSegue", sender as NSObject);
        }

        private void AnalysisResultView_ExpandDataButtonClicked(object sender, AnalysisResult e)
        {
            var storyboard = NSStoryboard.FromName("Main", null);
            var vc = storyboard.InstantiateControllerWithIdentifier("BindingAnalysisViewController")
                     as BindingAnalysisViewController;

            vc.SetResult(e);

            PresentViewControllerAsSheet(vc);

            //PerformSegue("ShowAnalysisResultSegue", this);
        }

        private void DataManager_SelectionDidChange(object sender, ExperimentData e)
        {
            if (_pendingRemovedRow.HasValue) return;
            SyncSelection();
        }

        private void DataManager_AnalysisResultSelected(object sender, AnalysisResult e)
        {
            //PerformSegue("ShowAnalysisResultSegue", this);
            if (_pendingRemovedRow.HasValue) return;
            SyncSelection();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            TableView.ColumnAutoresizingStyle = NSTableViewColumnAutoresizingStyle.FirstColumnOnly;

            DataNotProcessedImage = NotProcessedImage.Image;
            DataEnabledImage = IncludedImage.Image;
            DataDisabledImage = NotIncludedImage.Image;

            EnsureTableBindings();
            ReloadTable();
        }

        private void OnDataManagerUpdated(object sender, ExperimentData data)
        {
            var rows = DataManager.Source?.Content?.Count ?? -1;
            var selectedIndex = DataManager.Source?.SelectedIndex ?? -1;
            AppEventHandler.PrintAndLog(
                $"SideBar.OnDataManagerUpdated: pendingRemovedRow={_pendingRemovedRow?.ToString() ?? "<none>"}, payload={DescribeItem(data)}, rows={rows}, selectedIndex={selectedIndex}",
                1);

            if (_pendingRemovedRow.HasValue)
            {
                if (IsExpectedPendingRemovalUpdate(rows))
                {
                    _pendingRemovalModelUpdateObserved = true;
                    AppEventHandler.PrintAndLog("SideBar.OnDataManagerUpdated: skipped reload due to pending row removal", 1);
                    return;
                }

                ClearPendingRemoval("model update no longer matches pending row removal");
            }

            ReloadTable();
        }

        private void OnRowWillRemoveEvent(object sender, int e)
        {
            _pendingRemovedRow = e;
            _pendingRemovalSource = DataManager.Source;
            _pendingRemovalRowsBefore = DataManager.Source?.Content?.Count ?? -1;
            _pendingRemovalModelUpdateObserved = false;
            var item = DataManager.Source != null && e >= 0 && e < DataManager.Source.Content.Count
                ? DataManager.Source.Content[e]
                : null;
            AppEventHandler.PrintAndLog(
                $"SideBar.OnRowWillRemoveEvent: row={e}, item={DescribeItem(item)}, rows={DataManager.Source?.Content?.Count ?? -1}, sender={sender?.GetType().Name ?? "<null>"}");
        }

        private void OnRowRemoveEvent(object sender, int e)
        {
            AppEventHandler.PrintAndLog(
                $"SideBar.OnRowRemoveEvent: requestedRow={e}, pendingRemovedRow={_pendingRemovedRow?.ToString() ?? "<none>"}, rowsBefore={DataManager.Source?.Content?.Count ?? -1}, selectedIndexBefore={DataManager.Source?.SelectedIndex ?? -1}, sender={sender?.GetType().Name ?? "<null>"}");

            if (!_pendingRemovedRow.HasValue)
            {
                AppEventHandler.PrintAndLog("SideBar.OnRowRemoveEvent: no pending row, falling back to full reload", 1);
                ReloadTable();
                return;
            }

            try
            {
                TableView.BeginUpdates();
                TableView.RemoveRows(new NSIndexSet(_pendingRemovedRow.Value), NSTableViewAnimation.SlideLeft);
                TableView.EndUpdates();
                SyncSelection();
                AppEventHandler.PrintAndLog(
                    $"SideBar.OnRowRemoveEvent completed animated removal: removedRow={_pendingRemovedRow.Value}, rowsAfter={DataManager.Source?.Content?.Count ?? -1}, selectedIndexAfter={DataManager.Source?.SelectedIndex ?? -1}");
            }
            catch (Exception ex)
            {
                AppEventHandler.AddLog(ex);
                AppEventHandler.PrintAndLog("SideBar.OnRowRemoveEvent: animated removal failed, reloading table", 1);
                ReloadTable();
            }
            finally
            {
                ClearPendingRemoval("row remove event completed");
            }
        }

        private void DataManager_RemoveListIndices(object sender, int[] e)
        {
            AppEventHandler.PrintAndLog(
                $"SideBar.DataManager_RemoveListIndices: rows=[{string.Join(", ", e ?? Array.Empty<int>())}], rowsBeforeReload={DataManager.Source?.Content?.Count ?? -1}");
            ClearPendingRemoval("batch removal reload");
            ReloadTable();
        }

        bool IsExpectedPendingRemovalUpdate(int rows)
        {
            if (!_pendingRemovedRow.HasValue) return false;
            if (_pendingRemovalModelUpdateObserved) return false;
            if (!ReferenceEquals(DataManager.Source, _pendingRemovalSource)) return false;
            if (_pendingRemovalRowsBefore <= 0) return false;
            if (_pendingRemovedRow.Value < 0 || _pendingRemovedRow.Value >= _pendingRemovalRowsBefore) return false;

            return rows == _pendingRemovalRowsBefore - 1;
        }

        void ClearPendingRemoval(string reason)
        {
            if (!_pendingRemovedRow.HasValue)
            {
                _pendingRemovalSource = null;
                _pendingRemovalRowsBefore = -1;
                _pendingRemovalModelUpdateObserved = false;
                return;
            }

            AppEventHandler.PrintAndLog(
                $"SideBar: clearing pendingRemovedRow={_pendingRemovedRow.Value} ({reason})",
                1);
            _pendingRemovedRow = null;
            _pendingRemovalSource = null;
            _pendingRemovalRowsBefore = -1;
            _pendingRemovalModelUpdateObserved = false;
        }

        private void OnDataViewClicked(object sender, EventArgs e)
        {
            if (_suppressTableSelectionCallback) return;
            if ((int)TableView.SelectedRow != -1) DataManager.SelectIndex((int)TableView.SelectedRow);
        }

        

        #endregion

        void EnsureTableBindings()
        {
            if (TableView == null || DataManager.Source == null) return;

            if (TableView is ModifierClickTableView modifierClickTableView)
            {
                modifierClickTableView.RowModifierClicked -= OnTableRowModifierClicked;
                modifierClickTableView.RowModifierClicked += OnTableRowModifierClicked;
            }

            if (!ReferenceEquals(TableView.DataSource, DataManager.Source))
            {
                TableView.DataSource = DataManager.Source;
            }

            if (_tableDelegate == null || !ReferenceEquals(_tableDelegate.Source, DataManager.Source))
            {
                if (_tableDelegate != null)
                {
                    _tableDelegate.ExperimentDataViewClicked -= OnDataViewClicked;
                    _tableDelegate.RemoveRow -= OnRowRemoveEvent;
                }

                _tableDelegate = new ExperimentDataDelegate(DataManager.Source);
                _tableDelegate.ExperimentDataViewClicked += OnDataViewClicked;
                _tableDelegate.RemoveRow += OnRowRemoveEvent;
            }

            if (!ReferenceEquals(TableView.Delegate, _tableDelegate))
            {
                TableView.Delegate = _tableDelegate;
            }
        }

        void OnTableRowModifierClicked(object sender, ModifierClickTableViewEventArgs e)
        {
            if (DataManager.Source == null) return;
            if (e.Row < 0 || e.Row >= DataManager.Source.Content.Count) return;
            if (DataManager.Source.Content[e.Row] is not ExperimentData data) return;
            if (data.Processor?.IntegrationCompleted != true) return;

            data.Include = !data.Include;
            DataManager.InvokeDataInclusionDidChange();

            e.Handled = true;
        }

        void ReloadTable()
        {
            ClearPendingRemoval("full table reload");

            if (TableView == null || DataManager.Source == null)
            {
                AppEventHandler.PrintAndLog("SideBar.ReloadTable skipped: table or source was null", 1);
                return;
            }

            AppEventHandler.PrintAndLog(
                $"SideBar.ReloadTable: rows={DataManager.Source.Content.Count}, selectedIndex={DataManager.Source.SelectedIndex}, pendingRemovedRow={_pendingRemovedRow?.ToString() ?? "<none>"}",
                1);

            EnsureTableBindings();
            try
            {
                _suppressTableSelectionCallback = true;
                TableView.ReloadData();
                SyncSelection();
            }
            finally
            {
                _suppressTableSelectionCallback = false;
            }
        }

        void SyncSelection()
        {
            if (TableView == null || DataManager.Source == null)
            {
                AppEventHandler.PrintAndLog("SideBar.SyncSelection skipped: table or source was null", 1);
                return;
            }

            int idx = DataManager.Source.SelectedIndex;
            if (idx >= 0 && idx < DataManager.Source.Content.Count)
            {
                var wasSuppressingSelectionCallback = _suppressTableSelectionCallback;
                _suppressTableSelectionCallback = true;
                try
                {
                    TableView.SelectRow(idx, false);
                }
                finally
                {
                    _suppressTableSelectionCallback = wasSuppressingSelectionCallback;
                }
                AppEventHandler.PrintAndLog(
                    $"SideBar.SyncSelection: selectedIndex={idx}, selectedItem={DescribeItem(DataManager.Source.Content[idx])}",
                    1);
            }
            else
            {
                var wasSuppressingSelectionCallback = _suppressTableSelectionCallback;
                _suppressTableSelectionCallback = true;
                try
                {
                    TableView.DeselectAll(this);
                }
                finally
                {
                    _suppressTableSelectionCallback = wasSuppressingSelectionCallback;
                }
                AppEventHandler.PrintAndLog($"SideBar.SyncSelection: deselected all, selectedIndex={idx}, rows={DataManager.Source.Content.Count}", 1);
            }
        }
    }
}
