// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class AnalysisResultView : NSView
	{
        public event EventHandler<int> RemoveData;
        public static event EventHandler<AnalysisResult> ExpandDataButtonClicked;

        AnalysisITCDataSource source;
        AnalysisResult data;
        int ContentIndex => source.Content.IndexOf(data);

        public AnalysisResultView (IntPtr handle) : base (handle)
		{
		}

        internal void Setup(AnalysisITCDataSource source, AnalysisResult analysisResult, int row)
        {
            this.source = source;
            this.data = analysisResult;

            ResultTitleLabel.StringValue = analysisResult.FileName;
            ResultContentLabel.StringValue = analysisResult.GetResultString();
        }

        partial void ViewResultClick(NSObject sender)
        {
            ExpandDataButtonClicked?.Invoke(this, data);
        }

        partial void RemoveButtonClick(NSObject sender)
        {
            RemoveData?.Invoke(this, ContentIndex);

            DataManager.RemoveData(ContentIndex);
        }
    }
}
