// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class DataProcessingViewControllet : NSViewController
	{
        ExperimentData Data => DataManager.Current();
        DataProcessor Processor => Data.Processor;

		public DataProcessingViewControllet (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            DataManager.SelectionDidChange += OnSelectionChanged;
        }

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            UpdateUI();
        }

        void UpdateUI()
        {
            switch ((BaselineInterpolatorTypes)(int)InterpolatorTypeControl.SelectedSegment)
            {
                case BaselineInterpolatorTypes.Spline:
                    SplineAlgorithmView.Hidden = false;
                    SplineAlgoControl.Hidden = false;
                    SplineHandleModeView.Hidden = false;
                    break;
                case BaselineInterpolatorTypes.ASL:
                    SplineAlgorithmView.Hidden = true;
                    SplineAlgoControl.Hidden = true;
                    SplineHandleModeView.Hidden = true;
                    break;
            }
        }

        partial void InterplolatorClicked(NSSegmentedControl sender)
        {
            Processor.InitializeBaseline((BaselineInterpolatorTypes)(int)sender.SelectedSegment);

            UpdateUI();

            UpdateProcessing();
        }

        void UpdateProcessing()
        {
            Data.Processor.Interpolator.Interpolate();

            BaselineGraphView.Invalidate();
        }

        private void OnSelectionChanged(object sender, ExperimentData e)
        {
            BaselineGraphView.Initialize(DataManager.Current());
        }
    }
}
