// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class DataProcessingGraphView : NSView
	{
		public DataProcessingGraphView (IntPtr handle) : base (handle)
		{
		}
	}
}
