// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class ExperimentDetailsPopoverController : NSViewController
	{
        public static event EventHandler UpdateTable;

		public static ExperimentData Data { get; set; } = null;

        public ExperimentDetailsPopoverController() : base()
        {

        }

		public ExperimentDetailsPopoverController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

			CellConcentrationField.DoubleValue = Data.CellConcentration * 1000000;
			SyringeConcentrationField.DoubleValue = Data.SyringeConcentration * 1000000;
            TemperatureField.DoubleValue = Data.MeasuredTemperature;
        }

        partial void Apply(NSObject sender)
        {
            Data.SyringeConcentration = SyringeConcentrationField.DoubleValue / 1000000;
            Data.CellConcentration = CellConcentrationField.DoubleValue / 1000000;
            Data.MeasuredTemperature = TemperatureField.DoubleValue;

            DismissViewController(this);

            UpdateTable?.Invoke(this, null);
        }

        partial void Cancel(NSObject sender)
        {
            DismissViewController(this);
        }
    }
}
