// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace AnalysisITC
{
	public partial class FinalFigureGraphView : NSView
	{
		public FinalFigureGraphView (IntPtr handle) : base (handle)
		{
            GlobalAnalyzer.AnalysisFinished += (object sender, SolverConvergence e) => { this.NeedsDisplay = true; };
		}

        public override void DrawRect(CGRect dirtyRect)
        {
            base.DrawRect(dirtyRect);

            var graph = new FinalFigure(DataManager.Current, this);

            var cg = NSGraphicsContext.CurrentContext.CGContext;


            graph.Draw(cg, new CGPoint(dirtyRect.GetMidX(), dirtyRect.GetMidY()));
        }
    }
}
