// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class GuideHintViewController : NSViewController
	{
		public GuideHintViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();
        }

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            var img = NSImage.ImageNamed("ExperimentViewCell");


            ImageView.Image = img;
        }
    }
}
