// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class GuideHintViewController : NSViewController
	{
		public GuideHintViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
