// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class HelpViewController : NSViewController
	{
		public HelpViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            //var attributedString = HelpTextField.AttributedString;

            //var range = new NSRange(0, attributedString.Length);

            ////Console.WriteLine(attributedString.ToString());

            //var att = new NSAttributedStringDocumentAttributes()
            //{
            //    DocumentType = NSDocumentType.WordML
            //};

            //// Convert the attributed string to an NSData object
            //var data = attributedString.GetData(range, att.Dictionary, out NSError err);

            //// Convert the NSData object to a string
            //var htmlString = NSString.FromData(data, NSStringEncoding.UTF8);

            //Console.WriteLine(htmlString.ToString());
        }
    }
}
