// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

using AnalysisITC.Core.Application;
using AnalysisITC.Core.Analysis;
using AnalysisITC.Core.Analysis.Models;
using AnalysisITC.Core.Data;
using AnalysisITC.Core.DataReaders;
using AnalysisITC.Core.Export;
using AnalysisITC.Core.Numerics;
using AnalysisITC.Core.Presentation;
using AnalysisITC.Core.Processing;
using AnalysisITC.Core.Units;
using AnalysisITC.Core.Utilities;

namespace AnalysisITC
{
	public partial class DataGraphOptionPopoverViewController : NSViewController
	{
		public DataGraphOptionPopoverViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();
            FinalFigureOptionsController.SyncData(Controls);
        }

        partial void ControlChanged(NSObject sender)
        {
            FinalFigureOptionsController.ApplyData(Controls);
            FinalFigureGraphView.Invalidate();
        }

        FinalFigureOptionsController.DataControls Controls => new()
        {
            DrawBaseline = DrawBaseline,
            DrawCorrected = DrawCorrected,
            PowerAxisTitleLabel = PowerAxisTitleLabel,
            TimeAxisTitleLabel = TimeAxisTitleLabel,
            TimeUnitControl = TimeUnitControl,
            UnifiedPowerAxis = UnifiedPowerAxis,
            XTickLabel = XTickLabel,
            XTickStepper = XTickStepper,
            YTickLabel = YTickLabel,
            YTickStepper = YTickStepper,
        };
    }
}
