// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

using AnalysisITC.Core.Application;
using AnalysisITC.Core.Analysis;
using AnalysisITC.Core.Analysis.Models;
using AnalysisITC.Core.Data;
using AnalysisITC.Core.DataReaders;
using AnalysisITC.Core.Export;
using AnalysisITC.Core.Numerics;
using AnalysisITC.Core.Presentation;
using AnalysisITC.Core.Processing;
using AnalysisITC.Core.Units;
using AnalysisITC.Core.Utilities;

namespace AnalysisITC
{
	public partial class FitGraphOptionPopoverViewController : NSViewController
	{
		public FitGraphOptionPopoverViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();
            FinalFigureOptionsController.SyncFit(Controls);
        }

        partial void ControlClicked(NSObject sender)
        {
            FinalFigureOptionsController.ApplyFit(Controls);
            FinalFigureGraphView.Invalidate();
        }

        FinalFigureOptionsController.FitControls Controls => new()
        {
            AddGapToResidualPlot = AddGapToResidualPlot,
            BadDataErrorBars = BadDataErrorBars,
            DrawConfidence = DrawConfidence,
            DrawOffsetCorrected = DrawOffsetCorrected,
            DrawErrorBars = DrawErrorBars,
            DrawZeroLine = DrawZeroLine,
            EnthalpyAxisTitleLabel = EnthalpyAxisTitleLabel,
            HideBadData = HideBadData,
            MolarRatioAxisTitleLabel = MolarRatioAxisTitleLabel,
            ShowResiduals = ShowResiduals,
            SplineInterpolationControl = SplineInterpolationControl,
            SymbolControl = SymbolControl,
            SymbolSizeLabel = SymbolSizeLabel,
            SymbolSizeStepper = SymbolSizeStepper,
            UnifiedHeatAxis = UnifiedHeatAxis,
            UnifiedMolarRatioAxis = UnifiedMolarRatioAxis,
            XAxisTickStepper = XAxisTickStepper,
            XTickLabel = XTickLabel,
            YAxisTickStepper = YAxisTickStepper,
            YTickLabel = YTickLabel,
        };
    }
}
