// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using AppKit;
using AnalysisITC.Core;
using AnalysisITC.UI;

using AnalysisITC.Core.Application;
using AnalysisITC.Core.Analysis;
using AnalysisITC.Core.Analysis.Models;
using AnalysisITC.Core.Data;
using AnalysisITC.Core.DataReaders;
using AnalysisITC.Core.Export;
using AnalysisITC.Core.Numerics;
using AnalysisITC.Core.Presentation;
using AnalysisITC.Core.Processing;
using AnalysisITC.Core.Units;
using AnalysisITC.Core.Utilities;

namespace AnalysisITC
{
	public partial class PreferencesViewController : NSViewController
	{
        const double BootstrapIterationMinExponent = 1;
        const double BootstrapIterationMaxExponent = 3;

        ColorSchemes ColorScheme;

		public PreferencesViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var list = AppColors.GetColorSchemes();

            foreach (var scheme in list)
            {
                ColorMenu.AddItem(new NSMenuItem(scheme.ToString(), (sender, e) => ColorMenuHandler((NSMenuItem)sender,scheme))
                {
                    State = AppSettings.ColorScheme == scheme ? NSCellStateValue.On : NSCellStateValue.Off,
                });
            }
        }

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            ColorScheme = AppSettings.ColorScheme;
            ColorMenu.Items[0].Title = ColorScheme.ToString();
            ColorThemeModeControl.SelectedSegment = (int)AppSettings.ColorSchemeGradientMode;

            RefTempField.StringValue = AppSettings.ReferenceTemperature.ToString("F2");
            MinTempSpanSlider.DoubleValue = AppSettings.MinimumTemperatureSpanForFitting;
            TempSpanLabel.DoubleValue = AppSettings.MinimumTemperatureSpanForFitting;
            DefaultErrorMethodControl.SelectedSegment = (int)AppSettings.DefaultErrorEstimationMethod;
            IncludeConcVarianceCheck.State = AppSettings.IncludeConcentrationErrorsInBootstrap ? NSCellStateValue.On : NSCellStateValue.Off;
            DefaultBootstrapIterationSlider.DoubleValue = BootstrapIterationExponent(AppSettings.DefaultBootstrapIterations);
            FuncToleranceSlider.DoubleValue = -Math.Sqrt(-Math.Log10(AppSettings.OptimizerTolerance));
            EnergyUnitControl.SelectedSegment = AppSettings.EnergyUnit.IsSI() ? 0 : 1;
            DefaultBootstrapIterationLabel.StringValue = ((int)Math.Pow(10, DefaultBootstrapIterationSlider.DoubleValue)).ToString();
            ConcentrationAutoVarianceSlider.DoubleValue = 100 * AppSettings.ConcentrationAutoVariance;
            ConcentrationAutoVarianceLabel.StringValue = AppSettings.IsConcentrationAutoVarianceEnabled ? (100 * AppSettings.ConcentrationAutoVariance).ToString("F1") + "%" : "";

            SetFuncToleranceLabel(AppSettings.OptimizerTolerance);
        }

        public void ColorMenuHandler(NSMenuItem sender, ColorSchemes e)
        {
            ColorMenu.Items[0].Title = e.ToString();

            foreach (var item in ColorMenu.Items) item.State = NSCellStateValue.Off;

            sender.State = NSCellStateValue.On;

            ColorScheme = e;
        }

        partial void ConcentrationAutoVarianceSliderAction(NSSlider sender)
        {
            ConcentrationAutoVarianceLabel.StringValue = sender.DoubleValue > double.Epsilon ? sender.DoubleValue.ToString("F1") + "%" : "";
        }

        partial void DefaultBootstrapIterationAction(NSSlider sender)
        {
            DefaultBootstrapIterationLabel.StringValue = ((int)Math.Pow(10, BootstrapIterationExponent(DefaultBootstrapIterationSlider.DoubleValue, isExponent: true))).ToString();
        }

        partial void FuncToleranceAction(NSSlider sender)
        {
            var value = sender.DoubleValue;

            SetFuncToleranceLabel(Math.Pow(10, -(value * value)));
        }

        partial void Apply(NSObject sender)
        {
            if (double.TryParse(RefTempField.StringValue, out var val))
            {
                AppSettings.ReferenceTemperature = val;
            }

            var energyunit = EnergyUnitControl.SelectedSegment == 0 ? EnergyUnit.KiloJoule : EnergyUnit.KCal;

            if (energyunit.IsSI() != AppSettings.EnergyUnit.IsSI()) //Check if changed to other unit type, update if changed
            {
                AppSettings.EnergyUnit = energyunit;
            }

            AppSettings.MinimumTemperatureSpanForFitting = MinTempSpanSlider.DoubleValue;

            //Color
            AppSettings.ColorScheme = ColorScheme;
            AppSettings.ColorSchemeGradientMode = (ColorSchemeGradientMode)(int)ColorThemeModeControl.SelectedSegment;

            //Fitting
            AppSettings.DefaultErrorEstimationMethod = (ErrorEstimationMethod)(int)DefaultErrorMethodControl.SelectedSegment;
            AppSettings.IncludeConcentrationErrorsInBootstrap = IncludeConcVarianceCheck.State == NSCellStateValue.On;
            AppSettings.DefaultBootstrapIterations = (int)Math.Pow(10, BootstrapIterationExponent(DefaultBootstrapIterationSlider.DoubleValue, isExponent: true));
            AppSettings.OptimizerTolerance = Math.Max(Math.Pow(10, -(FuncToleranceSlider.DoubleValue * FuncToleranceSlider.DoubleValue)), double.Epsilon);
            AppSettings.ConcentrationAutoVariance = ConcentrationAutoVarianceSlider.DoubleValue / 100;

            AppSettings.Save();

            this.DismissViewController(this);
        }

        partial void Close(NSObject sender)
        {
            this.DismissViewController(this);
        }

        void SetFuncToleranceLabel(double value)
        {
            if (value < double.Epsilon) value = double.Epsilon;
            FuncToleranceLabel.DoubleValue = value;
        }

        static double BootstrapIterationExponent(double value, bool isExponent = false)
        {
            var exponent = isExponent ? value : Math.Log10(value);
            return Math.Max(BootstrapIterationMinExponent, Math.Min(BootstrapIterationMaxExponent, exponent));
        }
    }
}
