// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

using AnalysisITC.Core.Application;
using AnalysisITC.Core.Analysis;
using AnalysisITC.Core.Analysis.Models;
using AnalysisITC.Core.Data;
using AnalysisITC.Core.DataReaders;
using AnalysisITC.Core.Export;
using AnalysisITC.Core.Numerics;
using AnalysisITC.Core.Presentation;
using AnalysisITC.Core.Processing;
using AnalysisITC.Core.Units;
using AnalysisITC.Core.Utilities;

namespace AnalysisITC
{
	public partial class HuggingTextView : NSTextField
	{
		public HuggingTextView (IntPtr handle) : base (handle)
		{
		}

        [Export("initWithFrame:")]
        public HuggingTextView(CGRect frameRect) : base(frameRect)
        {

        }

        public override void MouseDown(NSEvent theEvent)
        {
            if (StringValue == "") StringValue = " ";

            base.MouseDown(theEvent);
        }

        public override void DidEndEditing(NSNotification notification)
        {
            StringValue = StringValue.Trim();

            base.DidEndEditing(notification);
        }
    }
}
