// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class AnalysisResultView : NSView
	{
        public event EventHandler<int> RemoveData;
        public static event EventHandler<AnalysisResult> ExpandDataButtonClicked;

        AnalysisITCDataSource source;
        AnalysisResult data;
        int ContentIndex => source?.Content?.FindIndex(x => x.UniqueID == data.UniqueID) ?? -1;
        int row = -1;

        public AnalysisResultView (IntPtr handle) : base (handle)
		{
		}

        internal void Setup(AnalysisITCDataSource source, AnalysisResult analysisResult, int row)
        {
            this.source = source;
            this.data = analysisResult;
            this.row = row;

            ResultTitleLabel.StringValue = analysisResult.FileName;
            ResultContentLabel.StringValue = analysisResult.GetResultString();
        }

        partial void ViewResultClick(NSObject sender)
        {
            ExpandDataButtonClicked?.Invoke(this, data);
        }

        partial void RemoveButtonClick(NSObject sender)
        {
            Console.WriteLine("BTN CLICK: " + data.UniqueID + " " + ContentIndex);
            foreach (var item in source.Content)
            {
                if (item is AnalysisResult)
                    Console.WriteLine("  " + item.UniqueID);
            }

            int idx = ContentIndex;

            DataManager.RemoveData2(idx);

            RemoveData?.Invoke(this, idx);
        }
    }
}
