// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Collections.Generic;
using AnalysisITC.Utilities;

namespace AnalysisITC
{
	public partial class ExperimentListViewController : NSViewController
	{
		public ExperimentListViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            var result = DataManager.DataSourceContent[DataManager.SelectedContentIndex];

            if (result is not AnalysisResult) throw new Exception("Selected item not analysis result");

            var analysisresult = result as AnalysisResult;

            Label.StringValue = "";

            var lines = new List<string>();

            foreach (var mdl in analysisresult.Solution.Model.Models)
            {
                lines.Add($"**{System.IO.Path.GetFileNameWithoutExtension(mdl.Data.FileName)}**");
                lines.Add($"  --Date: {mdl.Data.UIShortDateWithTime}");
                lines.Add($"  Temperature: {mdl.Data.MeasuredTemperature:G3}--");
            }

            Label.AttributedStringValue = MacStrings.FromMarkDownString(string.Join(Environment.NewLine, lines), Label.Font);
        }
    }
}
