// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using AppKit;
using AnalysisITC.AppClasses.Analysis2;
using AnalysisITC.AppClasses.Analysis2.Models;
using AnalysisITC.AppClasses.AnalysisClasses;

namespace AnalysisITC
{
    public partial class ResultViewDataSource : NSTableViewDataSource
    {
        public List<SolutionInterface> Data { get; private set; }

        public ConcentrationUnit KdUnit { get; set; } = ConcentrationUnit.µM;
        public EnergyUnit EnergyUnit { get; set; } = EnergyUnit.KiloJoule;
        public bool UseKelvin { get; set; } = false;

        public ResultViewDataSource(AnalysisResult result)
        {
            Data = result.Solution.Solutions;
        }

        public override nint GetRowCount(NSTableView tableView)
        {
            return Data.Count;
        }
    }

    public class ResultViewDelegate : NSTableViewDelegate
    {
        const string CellIdentifier = "Cell";

        public ConcentrationUnit KdUnit => DataSource.KdUnit;
        public EnergyUnit EnergyUnit => DataSource.EnergyUnit;
        public bool UseKelvin => DataSource.UseKelvin;

        private ResultViewDataSource DataSource;

        public ResultViewDelegate(ResultViewDataSource datasource)
        {
            this.DataSource = datasource;
        }

        public override NSView GetViewForItem(NSTableView tableView, NSTableColumn tableColumn, nint row)
        {
            // This pattern allows you reuse existing views when they are no-longer in use.
            // If the returned view is null, you instance up a new view
            // If a non-null view is returned, you modify it enough to reflect the new data
            NSTextField view = (NSTextField)tableView.MakeView(CellIdentifier, this);
            if (view == null)
            {
                view = new NSTextField();
                view.Identifier = CellIdentifier;
                view.BackgroundColor = NSColor.Clear;
                view.Bordered = false;
                view.Selectable = false;
                view.Editable = false;
            }

            // Setup view based on the column selected
            switch (tableColumn.Identifier)
            {
                case "Temp": view.StringValue = (DataSource.Data[(int)row].Temp + (UseKelvin ? 273.15 : 0)).ToString("F2"); break;
                case "IS": view.StringValue = (1000 * BufferAttribute.GetIonicStrength(DataSource.Data[(int)row].Data)).ToString("F1"); break;
                case "HPROT": view.StringValue = BufferAttribute.GetProtonationEnthalpy(DataSource.Data[(int)row].Data).ToString(EnergyUnit, "F1", withunit: false); break;
                case "N1": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.Nvalue1].AsNumber(); view.Alignment = NSTextAlignment.Center; break;
                case "N2": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.Nvalue2].AsNumber(); view.Alignment = NSTextAlignment.Center; break;
                case "Kd1": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.Affinity1].AsFormattedConcentration(KdUnit, withunit: false); view.Alignment = NSTextAlignment.Center; break;
                case "Kd2": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.Affinity2].AsFormattedConcentration(KdUnit, withunit: false); view.Alignment = NSTextAlignment.Center; break;
                case "∆H1": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.Enthalpy1].Energy.ToFormattedString(EnergyUnit, withunit: false); view.Alignment = NSTextAlignment.Center; break;
                case "∆H2": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.Enthalpy2].Energy.ToFormattedString(EnergyUnit, withunit: false); view.Alignment = NSTextAlignment.Center; break;
                case "-T∆S1": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.EntropyContribution1].Energy.ToFormattedString(EnergyUnit, withunit: false); view.Alignment = NSTextAlignment.Center; break;
                case "-T∆S2": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.EntropyContribution2].Energy.ToFormattedString(EnergyUnit, withunit: false); view.Alignment = NSTextAlignment.Center; break;
                case "∆G1": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.Gibbs1].Energy.ToFormattedString(EnergyUnit, withunit: false); view.Alignment = NSTextAlignment.Center; break;
                case "∆G2": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.Gibbs2].Energy.ToFormattedString(EnergyUnit, withunit: false); view.Alignment = NSTextAlignment.Center; break;
                case "Loss": view.StringValue = DataSource.Data[(int)row].Loss.ToString("G3"); view.Alignment = NSTextAlignment.Center; break;
                case "Keq": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.IsomerizationEquilibriumConstant].AsNumber(); view.Alignment = NSTextAlignment.Center; break;
                case "Kd_app": view.StringValue = DataSource.Data[(int)row].ReportParameters[ParameterType.ApparentAffinity].AsFormattedConcentration(KdUnit, withunit: false); view.Alignment = NSTextAlignment.Center; break;
                default: throw new NotImplementedException("[ResultViewDataSource.cs] Table column ID not recognized");
                    break;
            }

            return view;
        }
    }
}
