// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AnalysisITC.GUI.MacOS.Drawing;

namespace AnalysisITC
{
    public partial class AnalysisGraphView : NSGraph
    {
        static event EventHandler UpdateViewParameters;

        static bool showPeakInfo = true;
        static bool showFitParameters = true;
        static bool useUnifiedAxes = false;
        static bool showResidualGraph = true;

        public static bool ShowPeakInfo
        {
            get => showPeakInfo;
            set { showPeakInfo = value; UpdateViewParameters?.Invoke(null, null); }
        }
        public static bool ShowFitParameters
        {
            get => showFitParameters;
            set { showFitParameters = value; UpdateViewParameters?.Invoke(null, null); }
        }
        public static bool UseUnifiedAxes
        {
            get => useUnifiedAxes;
            set { useUnifiedAxes = value; UpdateViewParameters?.Invoke(null, null); }
        }
        public static bool ShowResidualGraph
        {
            get => showResidualGraph;
            set { showResidualGraph = value; UpdateViewParameters?.Invoke(null, null); }
        }
        public DataFittingGraph DataFittingGraph => Graph as DataFittingGraph;

        public AnalysisGraphView(IntPtr handle) : base(handle)
        {
            State = ProgramState.Analyze;

            UpdateViewParameters += AnalysisGraphView_UpdateViewParameters;
        }

        private void AnalysisGraphView_UpdateViewParameters(object sender, EventArgs e)
        {
            if (Graph == null) return;

            DataFittingGraph.ShowPeakInfo = ShowPeakInfo;
            DataFittingGraph.ShowFitParameters = ShowFitParameters;
            DataFittingGraph.UnifiedMolarRatioAxis = UseUnifiedAxes;
            DataFittingGraph.UnifiedEnthalpyAxis = UseUnifiedAxes;
            DataFittingGraph.ResidualDisplayOptions.ShowResidualGraph = ShowResidualGraph;

            Invalidate();
        }

        public override void Invalidate()
        {
            if (Graph == null) return;
            if (StateManager.CurrentState != State && State != ProgramState.AlwaysActive) return;

            base.Invalidate();
        }

        public void Initialize(ExperimentData experiment)
        {
            if (experiment != null)
            {
                Graph = new DataFittingGraph(experiment, this);

                AnalysisGraphView_UpdateViewParameters(null, null);
            }
            else Graph = null;

            Invalidate();
        }

        private void Experiment_SolutionChanged(object sender, EventArgs e)
        {
            Invalidate();
        }

        public override void MouseMoved(NSEvent theEvent)
        {
            base.MouseMoved(theEvent);

            if (Graph == null) return;

            var b = (Graph as DataFittingGraph).CursorFeatureFromPos(CursorPositionInView);

            if (b.IsMouseOverFeature)
            {
                NSCursor.PointingHandCursor.Set();

                ToolTip = b.ToolTip;

                Invalidate();
            }
            else
            {
                NSCursor.ArrowCursor.Set();

                ToolTip = null;
            }
        }

        public override void MouseDown(NSEvent theEvent)
        {
            base.MouseDown(theEvent);

            if (Graph == null) return;

            var b = Graph.CursorFeatureFromPos(CursorPositionInView, isclick: true);

            if (b.IsMouseOverFeature) NSCursor.PointingHandCursor.Set();
            else NSCursor.ArrowCursor.Set();

            Graph.IsMouseDown = true;

            Invalidate();
        }

        public override void MouseUp(NSEvent theEvent)
        {
            base.MouseUp(theEvent);

            if (Graph == null) return;

            var b = Graph.CursorFeatureFromPos(CursorPositionInView, ismouseup: true);

            if (b.IsMouseOverFeature) NSCursor.PointingHandCursor.Set();
            else NSCursor.ArrowCursor.Set();

            Graph.IsMouseDown = false;

            Invalidate();
        }
    }
}
