// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace AnalysisITC
{
	public partial class FinalFigureGraphView : NSView
	{
		public FinalFigureGraphView (IntPtr handle) : base (handle)
		{
            DataManager.SelectionDidChange += DataManager_SelectionDidChange;
		}

        private void DataManager_SelectionDidChange(object sender, ExperimentData e)
        {
            this.NeedsDisplay = true;
        }

        public override void DrawRect(CGRect dirtyRect)
        {
            base.DrawRect(dirtyRect);

            if (DataManager.Current == null) return;

            var graph = new FinalFigure(DataManager.Current, this);

            var cg = NSGraphicsContext.CurrentContext.CGContext;

            cg.SetFillColor(NSColor.SystemGray.CGColor);
            cg.FillRect(Frame);

            graph.Draw(cg, new CGPoint(dirtyRect.GetMidX(), dirtyRect.GetMidY()));
        }
    }
}
