// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using CoreGraphics;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AnalysisITC.AppClasses.AnalysisClasses;
using AnalysisITC.AppClasses.AnalysisClasses.Models;
using AnalysisITC.Utilities;

namespace AnalysisITC
{
    public partial class FinalFigureGraphView : NSView
    {
        static readonly ParameterType[] PdfMetadataParameterOrder = new[]
        {
            ParameterType.Offset,
            ParameterType.Nvalue1,
            ParameterType.Nvalue2,
            ParameterType.ApparentAffinity,
            ParameterType.Affinity1,
            ParameterType.Affinity2,
            ParameterType.Enthalpy1,
            ParameterType.Enthalpy2,
            ParameterType.EntropyContribution1,
            ParameterType.EntropyContribution2,
            ParameterType.Gibbs1,
            ParameterType.Gibbs2,
            ParameterType.HeatCapacity1,
            ParameterType.HeatCapacity2,
            ParameterType.IsomerizationEquilibriumConstant,
            ParameterType.IsomerizationRate,
            ParameterType.CisIsomerPopulationPercentage,
            ParameterType.Entropy1,
            ParameterType.Entropy2,
        };

        public static event EventHandler Invalidated;
        public static event EventHandler PlotSizeChanged;

        public static EnergyUnit EnergyUnit => AppSettings.EnergyUnit;
        //public FinalFigureDisplayParameters FinalFigureDisplayParameters => AppSettings.FinalFigureParameterDisplay;

        static string poweraxistitle = "";
        public static string PowerAxisTitle
        {
            get => poweraxistitle != "" ? poweraxistitle : "Differential Power (<unit>)";
            set
            {
                if (value == "") return;
                if (!value.Contains("<unit>")) value += " (<unit>)";

                poweraxistitle = value;
            }
        }
        public static bool PowerAxisTitleIsChanged => poweraxistitle == "";

        static string timeaxistitle = "";
        public static string TimeAxisTitle
        {
            get => timeaxistitle != "" ? timeaxistitle : "Time (<unit>)";
            set
            {
                if (value == "") return;
                if (!value.Contains("<unit>")) value += " (<unit>)";

                timeaxistitle = value;
            }
        }
        public static bool TimeAxisTitleIsChanged => timeaxistitle == "";

        static string enthalpyaxistitle = "";
        public static string EnthalpyAxisTitle
        {
            get => enthalpyaxistitle != "" ? enthalpyaxistitle : "<unit> of injectant";
            set
            {
                if (value == "") return;
                if (!value.Contains("<unit>")) value = "<unit> " + value;

                enthalpyaxistitle = value;
            }
        }
        public static bool EnthalpyAxisTitleAxisTitleIsChanged => enthalpyaxistitle == "";

        static string molarratioaxistitle = "";
        public static string MolarRatioAxisTitle
        {
            get => molarratioaxistitle != "" ? molarratioaxistitle : "Molar Ratio";
            set => molarratioaxistitle = value;
        }
        public static bool MolarRatioAxisTitleIsChanged => molarratioaxistitle == "";

        public static float Width { get; set; } = 6;
        public static float Height { get; set; } = 10;

        public static bool SanitizeTicks { get; set; } = true;
        public static int FitXTickCount { get; set; } = 7;
        public static int FitYTickCount { get; set; } = 7;
        public static int DataXTickCount { get; set; } = 7;
        public static int DataYTickCount { get; set; } = 7;

        public static bool ShowDataGraph { get; set; } = true;
        public static bool UnifiedEnthalpyAxis { get; set; } = false;
        public static bool UseUnifiedMolarRatioAxis { get; set; } = false;
        public static bool DrawZeroLine { get; set; } = true;
        public static bool ShowErrorBars { get; set; } = true;
        public static bool ShowBadDataErrorBars { get; set; } = false;
        public static bool DrawConfidence { get; set; } = true;
        public static bool DrawFitOffsetCorrected { get; set; } = true;
        public static bool DrawFitParameters { get; set; } = false;
        public static bool DrawExpDetails { get; set; } = true;
        public static bool DrawModelInfo { get; set; } = true;
        public static bool ShowTextUncertainties { get; set; } = true;
        public static UncertaintyDisplayStyle TextUncertaintyStyle { get; set; } = AppSettings.UncertaintyDisplayStyle;
        public static bool ShowBadData { get; set; } = true;
        public static float SymbolSize { get; set; } = CGGraph.SymbolSize;
        public static int SymbolShape { get; set; } = 0;
        public static bool ShowResiduals { get; set; } = false;
        public static bool GapResidualGraph { get; set; } = false;
        public static GraphBase.LineSmoothness FitLineSmoothness { get; set; } = AppSettings.FitLineSmoothness;
        public static bool AutoAxesIgnoresBadData { get; set; } = true;

        public static bool UnifiedPowerAxis { get; set; } = false;
        public static bool DrawBaseline { get; set; } = false;
        public static bool ShowIntegrationRegions { get; set; } = false;
        public static IntegrationRegionDisplayStyle IntegrationRegionDisplayStyle { get; set; } = IntegrationRegionDisplayStyle.Fill;
        public static bool DrawBaselineCorrected { get; set; } = true;
        public static string SyringeName { get; set; } = "";
        public static string CellName { get; set; } = "";
        public static bool UseNameAttributes { get; set; } = false;
        public static FinalFigureNameDisplayMode NameDisplayMode { get; set; } = FinalFigureNameDisplayMode.Name;
        public static bool ShowAxisTitles { get; set; } = true;
        public static double? DataXAxisMin { get; set; }
        public static double? DataXAxisMax { get; set; }
        public static double? DataYAxisMin { get; set; }
        public static double? DataYAxisMax { get; set; }
        public static double? FitXAxisMin { get; set; }
        public static double? FitXAxisMax { get; set; }
        public static double? FitYAxisMin { get; set; }
        public static double? FitYAxisMax { get; set; }
        public static TimeUnit TimeAxisUnit { get; set; } = TimeUnit.Minute;
        public static InformationBoxPlacement InformationBoxPosition { get; set; } = InformationBoxPlacement.Auto;
        public static BaselineDisplayStyle BaselineDisplayStyle { get; set; } = BaselineDisplayStyle.Solid;
        public static float BaselineThickness { get; set; } = 2f;

        public static FinalFigureDisplayParameters ParameterDisplayFlags =>
            FinalFigureDisplayParameters.Thermodynamic |
            FinalFigureDisplayParameters.Offset |
            FinalFigureDisplayParameters.Derived;

        public static FinalFigureDisplayParameters DetailDisplayFlags =>
            FinalFigureDisplayParameters.Temperature |
            FinalFigureDisplayParameters.Concentrations |
            FinalFigureDisplayParameters.InjectionDelay |
            FinalFigureDisplayParameters.Instrument |
            FinalFigureDisplayParameters.Attributes;

        public static FinalFigureDisplayParameters VisibleFinalFigureDisplayParameters
        {
            get
            {
                if (!DrawExpDetails) return FinalFigureDisplayParameters.None;

                var display = AppSettings.FinalFigureParameterDisplay & ParameterDisplayFlags;

                if (DrawModelInfo)
                {
                    display |= FinalFigureDisplayParameters.Model;
                }

                display |= AppSettings.FinalFigureParameterDisplay & DetailDisplayFlags;

                return display;
            }
        }

        public static void UpdateParameterBoxVisibility()
        {
            DrawFitParameters = DrawExpDetails
                && (DrawModelInfo || (AppSettings.FinalFigureParameterDisplay & ParameterDisplayFlags) != FinalFigureDisplayParameters.None);
        }

        public static void Invalidate() => Invalidated?.Invoke(null, null);

        FinalFigure graph;
        bool eventsUnsubscribed;
        public CGPoint Center { get; set; } = new CGPoint();

        public FinalFigureGraphView (IntPtr handle) : base (handle)
		{
            DataManager.SelectionDidChange += DataManager_SelectionDidChange;
            DataManager.ResultLinkedExperimentHighlightDidChange += DataManager_SelectionDidChange;
            Invalidated += FinalFigureGraphView_Invalidated;
            AppSettings.SettingsDidUpdate += FinalFigureGraphView_Invalidated;

            LayerContentsRedrawPolicy = NSViewLayerContentsRedrawPolicy.OnSetNeedsDisplay;
		}

        private void FinalFigureGraphView_Invalidated(object sender, EventArgs e)
        {
            InitializeGraph();

            this.NeedsDisplay = true;
        }

        private void DataManager_SelectionDidChange(object sender, ExperimentData e)
        {
            InitializeGraph();

            this.NeedsDisplay = true;
        }

        public static FinalFigure SetupForExport(ExperimentData experiment)
        {
            var _ = (new FinalFigure(experiment, new NSView(new CGRect(0, 0, 0, 0)))).PrintBox; //no idea what this does

            var _graph = new FinalFigure(experiment, new NSView(_))
            {
                PlotDimensions = new CGSize(Width, Height),
                SanitizeTicks = SanitizeTicks,

                PowerAxisTitle = PowerAxisTitle,
                TimeAxisTitle = TimeAxisTitle,
                UseUnifiedDataAxes = UnifiedPowerAxis,
                ShouldDrawBaseline = DrawBaseline,
                ShowIntegrationRegions = ShowIntegrationRegions,
                IntegrationRegionDisplayStyle = IntegrationRegionDisplayStyle,
                DrawBaselineCorrected = DrawBaselineCorrected,
                BaselineThickness = BaselineThickness,
                BaselineDisplayStyle = BaselineDisplayStyle,
                SyringeName = SyringeName,
                CellName = CellName,
                UseNameAttributes = UseNameAttributes,
                NameDisplayMode = NameDisplayMode,
                ShowAxisTitles = ShowAxisTitles,
                DataXAxisMin = DataXAxisMin,
                DataXAxisMax = DataXAxisMax,
                DataYAxisMin = DataYAxisMin,
                DataYAxisMax = DataYAxisMax,

                EnthalpyAxisTitle = EnthalpyAxisTitle,
                MolarRatioAxisTitle = MolarRatioAxisTitle,
                FitXAxisMin = FitXAxisMin,
                FitXAxisMax = FitXAxisMax,
                FitYAxisMin = FitYAxisMin,
                FitYAxisMax = FitYAxisMax,
                UseUnifiedAnalysisAxes = UseUnifiedMolarRatioAxis,
                UnifiedEnthalpyAxis = UnifiedEnthalpyAxis,
                ShowBadDataPoints = ShowBadData,
                ShowBadDataErrorBars = ShowBadDataErrorBars,
                ShowErrorBars = ShowErrorBars,
                DrawConfidence = DrawConfidence,
                DrawFitOffsetCorrected = DrawFitOffsetCorrected,
                DrawZeroLine = DrawZeroLine,
                DrawFitParameters = DrawFitParameters,
                DrawExpDetails = FinalFigureGraphView.DrawExpDetails,
                FinalFigureDisplayParameters = FinalFigureGraphView.VisibleFinalFigureDisplayParameters,
                InformationBoxPlacement = InformationBoxPosition,
                ShowTextUncertainties = ShowTextUncertainties,
                TextUncertaintyStyle = TextUncertaintyStyle,
                SymbolShape = (CGGraph.SymbolShape)SymbolShape,
                SymbolSize = SymbolSize,
                ShowResiduals = ShowResiduals,
                IncludeResidualGraphGap = GapResidualGraph,
                LineSmoothness = FitLineSmoothness,
                AutoAxesIgnoresBadData = AutoAxesIgnoresBadData,
                ShowDataGraph = ShowDataGraph,
            };

            _graph.SetTimeUnit(TimeAxisUnit);
            _graph.SetEnergyUnit(EnergyUnit);
            _graph.SetTickNumber(DataXTickCount, DataYTickCount, FitXTickCount, FitYTickCount);
            _graph.SetShowDataGraph(ShowDataGraph);

            return _graph;
        }

        public static void Export(ExportDataSelection selection)
        {
            var datas = GetExportData(selection).Where(d => d != null).ToList();
            if (datas.Count == 0)
            {
                AppEventHandler.DisplayHandledException(new HandledException(
                    HandledException.Severity.Warning,
                    "No Figures Selected",
                    "No final figures matched the current export selection."));
                return;
            }

            var dlg = new NSOpenPanel();
            dlg.Title = "Export Figures";
            dlg.Message = "Choose the output folder for the exported PDF figures.";
            dlg.Prompt = "Export";
            dlg.CanChooseDirectories = true;
            dlg.CanCreateDirectories = true;
            dlg.CanChooseFiles = false;


            dlg.BeginSheet(NSApplication.SharedApplication.MainWindow, (result) =>
            {
                if (result == (int)NSModalResponse.OK)
                {
                    var folderPath = dlg.Url?.Path;
                    if (string.IsNullOrWhiteSpace(folderPath)) return;

                    var exportTargets = CreateFigureExportTargets(datas, folderPath);
                    if (!ConfirmOverwriteIfNeeded(NSApplication.SharedApplication.MainWindow, exportTargets.Select(t => t.Path)))
                        return;

                    foreach (var target in exportTargets)
                    {
                        WriteFigurePdf(target.Data, target.Path);
                    }
                }
            });
        }

        public static void Export(AnalysisResult result)
        {
            if (result == null)
            {
                AppEventHandler.DisplayHandledException(new HandledException(
                    HandledException.Severity.Warning,
                    "No Analysis Result Selected",
                    "Select an analysis result before exporting associated final figures."));
                return;
            }

            var validityReport = result.ValidityReport;
            if (!validityReport.IsValid)
            {
                var reasons = validityReport.Reasons ?? new List<string>();
                var reason = reasons.Count > 0
                    ? string.Join(Environment.NewLine, reasons)
                    : "The analysis result does not match the current experiment data.";

                AppEventHandler.DisplayHandledException(new HandledException(
                    HandledException.Severity.Warning,
                    "Invalid Analysis Result",
                    "Associated final figures can only be exported for analysis results that are valid for the current data."
                    + Environment.NewLine + Environment.NewLine + reason));
                return;
            }

            var datas = result.Solution?.Solutions?
                .Where(solution => solution?.Data != null)
                .Select(solution => solution.Data)
                .ToList() ?? new List<ExperimentData>();

            if (datas.Count == 0)
            {
                AppEventHandler.DisplayHandledException(new HandledException(
                    HandledException.Severity.Warning,
                    "No Figures Selected",
                    "The selected analysis result does not contain any experiments to export."));
                return;
            }

            var dlg = new NSOpenPanel();
            dlg.Title = "Export Analysis Result Figures";
            dlg.Message = "Choose the parent folder for the exported PDF figures.";
            dlg.Prompt = "Export";
            dlg.CanChooseDirectories = true;
            dlg.CanCreateDirectories = true;
            dlg.CanChooseFiles = false;

            dlg.BeginSheet(NSApplication.SharedApplication.MainWindow, (modalResult) =>
            {
                if (modalResult != (int)NSModalResponse.OK) return;

                var parentFolderPath = dlg.Url?.Path;
                if (string.IsNullOrWhiteSpace(parentFolderPath)) return;

                var resultFolderPath = Path.Combine(parentFolderPath, SanitizeFileName(result.Name));
                var exportTargets = CreateFigureExportTargets(
                    datas,
                    resultFolderPath,
                    data => $"{data.Name}");

                if (!ConfirmOverwriteIfNeeded(NSApplication.SharedApplication.MainWindow, exportTargets.Select(t => t.Path)))
                    return;

                try
                {
                    Directory.CreateDirectory(resultFolderPath);
                }
                catch (Exception ex)
                {
                    AppEventHandler.DisplayHandledException(new HandledException(
                        HandledException.Severity.Error,
                        "Could Not Create Export Folder",
                        $"Could not create the export folder:\n{resultFolderPath}\n\n{ex.Message}"));
                    return;
                }

                DataManager.LoadResultSolutionsToExperiments(result);
                DataManager.InvokeUpdateDataViewCells();
                DataAnalysisViewController.InvalidateGraph();

                foreach (var target in exportTargets)
                {
                    WriteFigurePdf(target.Data, target.Path);
                }

                StatusBarManager.SetStatus("Analysis result figures exported", 3000);
            });
        }

        static List<FigureExportTarget> CreateFigureExportTargets(List<ExperimentData> datas, string folderPath)
        {
            return CreateFigureExportTargets(datas, folderPath, data => data.Name);
        }

        static List<FigureExportTarget> CreateFigureExportTargets(IEnumerable<ExperimentData> datas, string folderPath, Func<ExperimentData, string> nameFactory)
        {
            var targets = new List<FigureExportTarget>();
            var usedFileNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var data in datas)
            {
                var baseFileName = SanitizeFileName(nameFactory(data));
                var fileName = baseFileName + ".pdf";
                var suffix = 2;

                while (usedFileNames.Contains(fileName))
                {
                    fileName = $"{baseFileName} ({suffix}).pdf";
                    suffix++;
                }

                usedFileNames.Add(fileName);
                targets.Add(new FigureExportTarget(data, Path.Combine(folderPath, fileName)));
            }

            return targets;
        }

        static void WriteFigurePdf(ExperimentData data, string outputPath)
        {
            var g = FinalFigureGraphView.SetupForExport(data);
            var path = NSUrl.CreateFileUrl(outputPath, null);
            var parameters = BuildPdfMetadataKeywords(data);

            var pdfInfo = new CGPDFInfo
            {
                Title = data.Name,
                Author = MarkdownStrings.AppName,
                Creator = $"{MarkdownStrings.AppName} v{AppVersion.FullVersionString}",
                Subject = $"ITC publication figure",
                Keywords = parameters.ToArray(),
            };

            var x = new CGContextPDF(path, pdfInfo);
            x.BeginPage(new CGRect(new CGPoint(0, 0), g.PrintBox.Size));
            g.Draw(x, new CGPoint(g.PrintBox.Width / 2, g.PrintBox.Height / 2));
            x.EndPage();
            x.Close();
            path.Dispose();
        }

        static string SanitizeFileName(string name)
        {
            var cleanName = string.IsNullOrWhiteSpace(name) ? "Untitled Figure" : name.Trim();

            foreach (var invalidChar in Path.GetInvalidFileNameChars())
            {
                cleanName = cleanName.Replace(invalidChar, '_');
            }

            return string.IsNullOrWhiteSpace(cleanName) ? "Untitled Figure" : cleanName;
        }

        static bool ConfirmOverwriteIfNeeded(NSWindow parent, IEnumerable<string> outputPaths)
        {
            var existing = outputPaths.Where(File.Exists).Distinct(StringComparer.OrdinalIgnoreCase).ToList();
            if (existing.Count == 0) return true;

            var alert = new NSAlert
            {
                AlertStyle = NSAlertStyle.Warning,
                MessageText = "File already exists.",
                InformativeText = existing.Count == 1
                    ? $"This export will overwrite:\n{Path.GetFileName(existing[0])}"
                    : $"This export will overwrite {existing.Count} files."
            };

            alert.AddButton("Overwrite");
            alert.AddButton("Cancel");

            var response = parent != null ? alert.RunSheetModal(parent) : alert.RunModal();
            return response == (int)NSAlertButtonReturn.First;
        }

        class FigureExportTarget
        {
            public FigureExportTarget(ExperimentData data, string path)
            {
                Data = data;
                Path = path;
            }

            public ExperimentData Data { get; }
            public string Path { get; }
        }

        static IEnumerable<ExperimentData> GetExportData(ExportDataSelection selection)
        {
            switch (selection)
            {
                default:
                case ExportDataSelection.SelectedData:
                    return new[] { CurrentFigureData };
                case ExportDataSelection.IncludedData:
                    return DataManager.IncludedData;
                case ExportDataSelection.AllData:
                    return DataManager.Data.Where(d => d.Solution != null);
            }
        }

        static ExperimentData CurrentFigureData
        {
            get
            {
                if (DataManager.SelectedSolutionExperimentHighlight != null)
                {
                    return DataManager.SelectedSolutionExperimentHighlight;
                }

                if (DataManager.SelectedIsData
                    && DataManager.SelectedContentIndex >= 0
                    && DataManager.SelectedContentIndex < DataManager.SourceItems.Count
                    && DataManager.SourceItems[DataManager.SelectedContentIndex] is ExperimentData selectedData)
                {
                    return selectedData;
                }

                return DataManager.Current;
            }
        }

        static string[] BuildPdfMetadataKeywords(ExperimentData data)
        {
            var parameters = new List<string>()
            {
                $"Name: {data.Name}",
                $"File: {data.FileName}",
                $"File Date: {data.Date:yyyy-MM-dd}",
                $"[Syringe]: {data.SyringeConcentration.AsConcentration(ConcentrationUnit.µM, true)}",
                $"[Cell]: {data.CellConcentration.AsConcentration(ConcentrationUnit.µM, true)}",
                $"Model: {GetModelMetadata(data)}",
                $"Solution: {GetSolutionScope(data.Solution)}",
                $"Loss: {GetLossMetadata(data.Solution)}"
            };

            if (data.Solution == null) return parameters.Select(p => p.Replace(",", "..")).ToArray();

            var reportParameters = data.Solution.ReportParameters ?? new Dictionary<ParameterType, FloatWithError>();
            var ordered = new List<KeyValuePair<ParameterType, FloatWithError>>();

            foreach (var key in PdfMetadataParameterOrder)
            {
                if (reportParameters.ContainsKey(key))
                {
                    ordered.Add(new KeyValuePair<ParameterType, FloatWithError>(key, reportParameters[key]));
                    continue;
                }

                if (data.Solution.Parameters.ContainsKey(key))
                {
                    ordered.Add(new KeyValuePair<ParameterType, FloatWithError>(key, data.Solution.Parameters[key]));
                }
            }

            foreach (var par in ordered)
            {
                parameters.Add($"{GetParameterMetadataLabel(par.Key)} = {FormatParameterMetadataValue(par.Key, par.Value)}");
            }

            return parameters.Select(p => p.Replace(",", "..")).ToArray();
        }

        static string GetModelMetadata(ExperimentData data)
        {
            if (data?.Solution == null) return "";

            return data.Solution.ModelType.GetProperties()?.Name ?? data.Solution.ModelType.ToString();
        }

        static string GetSolutionScope(SolutionInterface solution)
        {
            if (solution == null) return "";

            return solution.IsGlobalAnalysisSolution ? "Global" : "Single";
        }

        static string GetLossMetadata(SolutionInterface solution)
        {
            if (solution == null) return "";

            return solution.Loss.ToString("G3");
        }

        static string GetParameterMetadataLabel(ParameterType key)
        {
            return key switch
            {
                ParameterType.Nvalue1 => "N",
                ParameterType.Nvalue2 => "N2",
                ParameterType.Affinity1 => "Kd",
                ParameterType.Affinity2 => "Kd2",
                ParameterType.ApparentAffinity => "Kd app",
                ParameterType.Enthalpy1 => "ΔH",
                ParameterType.Enthalpy2 => "ΔH2",
                ParameterType.EntropyContribution1 => "-TΔS",
                ParameterType.EntropyContribution2 => "-TΔS2",
                ParameterType.Gibbs1 => "ΔG",
                ParameterType.Gibbs2 => "ΔG2",
                ParameterType.HeatCapacity1 => "ΔCp",
                ParameterType.HeatCapacity2 => "ΔCp2",
                ParameterType.IsomerizationEquilibriumConstant => "Keq",
                ParameterType.IsomerizationRate => "kiso",
                ParameterType.CisIsomerPopulationPercentage => "%cis",
                _ => key.GetProperties().Name
            };
        }

        static string FormatParameterMetadataValue(ParameterType key, FloatWithError value)
        {
            var parent = key.GetProperties().ParentType;
            var energyUnit = AppClasses.AnalysisClasses.Models.Model.ReportEnergyUnit;
            var uncertaintyStyle = UncertaintyDisplayStyle.StandardDeviationAndConfidenceInterval;

            return parent switch
            {
                ParameterType.Affinity1 => value.AsFormattedConcentration(withunit: true, style: uncertaintyStyle),
                ParameterType.Enthalpy1 => value.Energy.ToFormattedString(energyUnit, permole: true, style: uncertaintyStyle),
                ParameterType.EntropyContribution1 => value.Energy.ToFormattedString(energyUnit, permole: true, style: uncertaintyStyle),
                ParameterType.Gibbs1 => value.Energy.ToFormattedString(energyUnit, permole: true, style: uncertaintyStyle),
                ParameterType.Offset => value.Energy.ToFormattedString(energyUnit, permole: true, style: uncertaintyStyle),
                ParameterType.HeatCapacity1 => value.Energy.ToFormattedString(energyUnit, permole: true, perK: true, style: uncertaintyStyle),
                _ => value.AsNumber(uncertaintyStyle),
            };
        }

        void InitializeGraph()
        {
            if (StateManager.CurrentState != ProgramState.Publish) return;
            var data = CurrentFigureData;
            if (data == null) return;

            graph = new FinalFigure(data, this)
            {
                PlotDimensions = new CGSize(Width, Height),
                SanitizeTicks = SanitizeTicks,

                PowerAxisTitle = PowerAxisTitle,
                TimeAxisTitle = TimeAxisTitle,
                UseUnifiedDataAxes = UnifiedPowerAxis,
                ShouldDrawBaseline = DrawBaseline,
                ShowIntegrationRegions = ShowIntegrationRegions,
                IntegrationRegionDisplayStyle = IntegrationRegionDisplayStyle,
                DrawBaselineCorrected = DrawBaselineCorrected,
                BaselineThickness = BaselineThickness,
                BaselineDisplayStyle = BaselineDisplayStyle,
                SyringeName = SyringeName,
                CellName = CellName,
                UseNameAttributes = UseNameAttributes,
                NameDisplayMode = NameDisplayMode,
                ShowAxisTitles = ShowAxisTitles,
                DataXAxisMin = DataXAxisMin,
                DataXAxisMax = DataXAxisMax,
                DataYAxisMin = DataYAxisMin,
                DataYAxisMax = DataYAxisMax,

                EnthalpyAxisTitle = EnthalpyAxisTitle,
                MolarRatioAxisTitle = MolarRatioAxisTitle,
                FitXAxisMin = FitXAxisMin,
                FitXAxisMax = FitXAxisMax,
                FitYAxisMin = FitYAxisMin,
                FitYAxisMax = FitYAxisMax,
                UseUnifiedAnalysisAxes = UseUnifiedMolarRatioAxis,
                UnifiedEnthalpyAxis = UnifiedEnthalpyAxis,
                ShowBadDataPoints = ShowBadData,
                ShowBadDataErrorBars = ShowBadDataErrorBars,
                ShowErrorBars = ShowErrorBars,
                DrawConfidence = DrawConfidence,
                DrawFitOffsetCorrected = DrawFitOffsetCorrected,
                DrawZeroLine = DrawZeroLine,
                DrawFitParameters = DrawFitParameters,
                DrawExpDetails = FinalFigureGraphView.DrawExpDetails,
                FinalFigureDisplayParameters = FinalFigureGraphView.VisibleFinalFigureDisplayParameters,
                InformationBoxPlacement = InformationBoxPosition,
                ShowTextUncertainties = ShowTextUncertainties,
                TextUncertaintyStyle = TextUncertaintyStyle,
                SymbolShape = (CGGraph.SymbolShape)SymbolShape,
                SymbolSize = SymbolSize,
                ShowResiduals = ShowResiduals,
                IncludeResidualGraphGap = GapResidualGraph,
                LineSmoothness = FitLineSmoothness,
                AutoAxesIgnoresBadData = AutoAxesIgnoresBadData,
                ShowDataGraph = ShowDataGraph,
            };

            graph.SetTimeUnit(TimeAxisUnit);
            graph.SetEnergyUnit(EnergyUnit);
            graph.SetTickNumber(DataXTickCount, DataYTickCount, FitXTickCount, FitYTickCount);
            graph.SetShowDataGraph(ShowDataGraph);

            SetFrameSize(graph.PrintBox.Size); 

            PlotSizeChanged?.Invoke(graph, null);
        }

        public void Export()
        {
            //Print(this);

            var path = NSFileManager.DefaultManager.GetUrl(NSSearchPathDirectory.DesktopDirectory, NSSearchPathDomain.All, NSUrl.FromFilename("test.pdf"), true, out NSError error);

            var url = NSUrl.FromFilename(new NSUrl("test.pdf", path.Path).Path);

            var x = new CGContextPDF(url);
            x.BeginPage(graph.PrintBox);

            graph.Draw(x, new CGPoint(Frame.Width / 2, Frame.Height / 2));
            x.EndPage();
            x.Close();
        }

        public override void DrawRect(CGRect dirtyRect)
        {
            if (StateManager.CurrentState != ProgramState.Publish) return;
            if (CurrentFigureData == null) return;
            if (graph == null) { InitializeGraph(); }

            base.DrawRect(dirtyRect);

            var cg = NSGraphicsContext.CurrentContext.CGContext;

            graph.Draw(cg, new CGPoint(Frame.Width / 2, Frame.Height / 2));
        }

        public void Print()
        {
            var scalingfactor = 1 / 1.576f;

            var op = NSPrintOperation.FromView(this);
            op.PrintInfo.PaperSize = this.Frame.Size.ScaleBy(scalingfactor);
            op.PrintInfo.BottomMargin = 0;
            op.PrintInfo.TopMargin = 0;
            op.PrintInfo.LeftMargin = 0;
            op.PrintInfo.RightMargin = 0;
            op.PrintInfo.ScalingFactor = scalingfactor;
            op.RunOperation();
        }

        void UnsubscribeEvents()
        {
            if (eventsUnsubscribed) return;
            eventsUnsubscribed = true;

            DataManager.SelectionDidChange -= DataManager_SelectionDidChange;
            DataManager.ResultLinkedExperimentHighlightDidChange -= DataManager_SelectionDidChange;
            Invalidated -= FinalFigureGraphView_Invalidated;
            AppSettings.SettingsDidUpdate -= FinalFigureGraphView_Invalidated;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) UnsubscribeEvents();

            base.Dispose(disposing);
        }
    }
}
