// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using CoreGraphics;
using System.Collections.Generic;
using System.Linq;
using AnalysisITC.AppClasses.AnalysisClasses;
using AnalysisITC.AppClasses.AnalysisClasses.Models;
using AnalysisITC.Utilities;

namespace AnalysisITC
{
    public partial class FinalFigureGraphView : NSView
    {
        static readonly ParameterType[] PdfMetadataParameterOrder = new[]
        {
            ParameterType.Offset,
            ParameterType.Nvalue1,
            ParameterType.Nvalue2,
            ParameterType.ApparentAffinity,
            ParameterType.Affinity1,
            ParameterType.Affinity2,
            ParameterType.Enthalpy1,
            ParameterType.Enthalpy2,
            ParameterType.EntropyContribution1,
            ParameterType.EntropyContribution2,
            ParameterType.Gibbs1,
            ParameterType.Gibbs2,
            ParameterType.HeatCapacity1,
            ParameterType.HeatCapacity2,
            ParameterType.IsomerizationEquilibriumConstant,
            ParameterType.IsomerizationRate,
            ParameterType.CisIsomerPopulationPercentage,
            ParameterType.Entropy1,
            ParameterType.Entropy2,
        };

        public static event EventHandler Invalidated;
        public static event EventHandler PlotSizeChanged;

        public static EnergyUnit EnergyUnit => AppSettings.EnergyUnit;
        //public FinalFigureDisplayParameters FinalFigureDisplayParameters => AppSettings.FinalFigureParameterDisplay;

        static string poweraxistitle = "";
        public static string PowerAxisTitle
        {
            get => poweraxistitle != "" ? poweraxistitle : "Differential Power (<unit>)";
            set
            {
                if (value == "") return;
                if (!value.Contains("<unit>")) value += " (<unit>)";

                poweraxistitle = value;
            }
        }
        public static bool PowerAxisTitleIsChanged => poweraxistitle == "";

        static string timeaxistitle = "";
        public static string TimeAxisTitle
        {
            get => timeaxistitle != "" ? timeaxistitle : "Time (<unit>)";
            set
            {
                if (value == "") return;
                if (!value.Contains("<unit>")) value += " (<unit>)";

                timeaxistitle = value;
            }
        }
        public static bool TimeAxisTitleIsChanged => timeaxistitle == "";

        static string enthalpyaxistitle = "";
        public static string EnthalpyAxisTitle
        {
            get => enthalpyaxistitle != "" ? enthalpyaxistitle : "<unit> of injectant";
            set
            {
                if (value == "") return;
                if (!value.Contains("<unit>")) value = "<unit> " + value;

                enthalpyaxistitle = value;
            }
        }
        public static bool EnthalpyAxisTitleAxisTitleIsChanged => enthalpyaxistitle == "";

        static string molarratioaxistitle = "";
        public static string MolarRatioAxisTitle
        {
            get => molarratioaxistitle != "" ? molarratioaxistitle : "Molar Ratio";
            set => molarratioaxistitle = value;
        }
        public static bool MolarRatioAxisTitleIsChanged => molarratioaxistitle == "";

        public static float Width { get; set; } = 6;
        public static float Height { get; set; } = 10;

        public static bool SanitizeTicks { get; set; } = true;
        public static int FitXTickCount { get; set; } = 7;
        public static int FitYTickCount { get; set; } = 7;
        public static int DataXTickCount { get; set; } = 7;
        public static int DataYTickCount { get; set; } = 7;

        public static bool ShowDataGraph { get; set; } = true;
        public static bool UnifiedEnthalpyAxis { get; set; } = false;
        public static bool UseUnifiedMolarRatioAxis { get; set; } = false;
        public static bool DrawZeroLine { get; set; } = true;
        public static bool ShowErrorBars { get; set; } = true;
        public static bool ShowBadDataErrorBars { get; set; } = false;
        public static bool DrawConfidence { get; set; } = true;
        public static bool DrawFitParameters { get; set; } = false;
        public static bool ShowBadData { get; set; } = true;
        public static float SymbolSize { get; set; } = CGGraph.SymbolSize;
        public static int SymbolShape { get; set; } = 0;
        public static bool ShowResiduals { get; set; } = false;
        public static bool GapResidualGraph { get; set; } = false;
        public static bool MirrorDataGraphAxisUnification { get; set; } = false;
        public static GraphBase.LineSmoothness FitLineSmoothness { get; set; } = AppSettings.FitLineSmoothness;
        public static bool AutoAxesIgnoresBadData { get; set; } = true;

        public static bool UnifiedPowerAxis { get; set; } = false;
        public static bool DrawBaseline { get; set; } = false;
        public static bool DrawBaselineCorrected { get; set; } = true;
        public static TimeUnit TimeAxisUnit { get; set; } = TimeUnit.Minute;

        public static void Invalidate() => Invalidated?.Invoke(null, null);

        FinalFigure graph;
        public CGPoint Center { get; set; } = new CGPoint();

        public FinalFigureGraphView (IntPtr handle) : base (handle)
		{
            DataManager.SelectionDidChange += DataManager_SelectionDidChange;
            Invalidated += FinalFigureGraphView_Invalidated;

            LayerContentsRedrawPolicy = NSViewLayerContentsRedrawPolicy.OnSetNeedsDisplay;
		}

        private void FinalFigureGraphView_Invalidated(object sender, EventArgs e)
        {
            InitializeGraph();

            this.NeedsDisplay = true;
        }

        private void DataManager_SelectionDidChange(object sender, ExperimentData e)
        {
            InitializeGraph();

            this.NeedsDisplay = true;
        }

        public static FinalFigure SetupForExport(ExperimentData experiment)
        {
            var _ = (new FinalFigure(experiment, new NSView(new CGRect(0, 0, 0, 0)))).PrintBox; //no idea what this does

            var _graph = new FinalFigure(experiment, new NSView(_))
            {
                PlotDimensions = new CGSize(Width, Height),
                SanitizeTicks = SanitizeTicks,

                PowerAxisTitle = PowerAxisTitle,
                TimeAxisTitle = TimeAxisTitle,
                UseUnifiedDataAxes = UnifiedPowerAxis,
                ShouldDrawBaseline = DrawBaseline,
                DrawBaselineCorrected = DrawBaselineCorrected,

                EnthalpyAxisTitle = EnthalpyAxisTitle,
                MolarRatioAxisTitle = MolarRatioAxisTitle,
                UseUnifiedAnalysisAxes = UseUnifiedMolarRatioAxis,
                UnifiedEnthalpyAxis = UnifiedEnthalpyAxis,
                ShowBadDataPoints = ShowBadData,
                ShowBadDataErrorBars = ShowBadDataErrorBars,
                ShowErrorBars = ShowErrorBars,
                DrawConfidence = DrawConfidence,
                DrawZeroLine = DrawZeroLine,
                DrawFitParameters = DrawFitParameters,
                DrawExpDetails = DrawFitParameters, //TODO implement separate option
                FinalFigureDisplayParameters = AppSettings.FinalFigureParameterDisplay,
                SymbolShape = (CGGraph.SymbolShape)SymbolShape,
                SymbolSize = SymbolSize,
                ShowResiduals = ShowResiduals,
                IncludeResidualGraphGap = GapResidualGraph,
                LineSmoothness = FitLineSmoothness,
                AutoAxesIgnoresBadData = AutoAxesIgnoresBadData,
                ShowDataGraph = ShowDataGraph,
            };

            _graph.SetTimeUnit(TimeAxisUnit);
            _graph.SetEnergyUnit(EnergyUnit);
            _graph.SetTickNumber(DataXTickCount, DataYTickCount, FitXTickCount, FitYTickCount);
            _graph.SetShowDataGraph(ShowDataGraph);

            return _graph;
        }

        public static void Export(ExportDataSelection selection)
        {
            IEnumerable<ExperimentData> datas;
            switch (selection)
            {
                default:
                case ExportDataSelection.SelectedData: datas = new ExperimentData[] { DataManager.Current }; break;
                case ExportDataSelection.IncludedData: datas = DataManager.IncludedData; break;
                case ExportDataSelection.AllData: datas = DataManager.Data.Where(d => d.Solution != null); break;
            }

            var dlg = new NSOpenPanel();
            dlg.Title = "Export Figures";
            dlg.Message = "Choose the output folder for the exported PDF figures.";
            dlg.Prompt = "Export";
            dlg.CanChooseDirectories = true;
            dlg.CanCreateDirectories = true;
            dlg.CanChooseFiles = false;


            dlg.BeginSheet(NSApplication.SharedApplication.MainWindow, (result) =>
            {
                if (result == 1)
                {
                    foreach (var data in datas)
                    {
                        var g = FinalFigureGraphView.SetupForExport(data);
                        var filename = data.Name;
                        var path = NSUrl.CreateFileUrl(dlg.Url.RelativePath + "/" + filename + ".pdf", null);
                        var parameters = BuildPdfMetadataKeywords(data);

                        var pdfInfo = new CGPDFInfo
                        {
                            Title = data.Name,
                            Author = MarkdownStrings.AppName,
                            Creator = $"{MarkdownStrings.AppName} v{AppVersion.FullVersionString}",
                            Subject = $"ITC publication figure",
                            Keywords = parameters.ToArray(),
                        };

                        var x = new CGContextPDF(path, pdfInfo);
                        x.BeginPage(new CGRect(new CGPoint(0, 0), g.PrintBox.Size));
                        g.Draw(x, new CGPoint(g.PrintBox.Width / 2, g.PrintBox.Height / 2));
                        x.EndPage();
                        x.Close();
                        path.Dispose();
                    }
                }
            });
        }

        static string[] BuildPdfMetadataKeywords(ExperimentData data)
        {
            var parameters = new List<string>()
            {
                $"Name: {data.Name}",
                $"File: {data.FileName}",
                $"File Date: {data.Date:yyyy-MM-dd}",
                $"[Syringe]: {data.SyringeConcentration.AsConcentration(ConcentrationUnit.µM, true)}",
                $"[Cell]: {data.CellConcentration.AsConcentration(ConcentrationUnit.µM, true)}",
                $"Model: {GetModelMetadata(data)}",
                $"Solution: {GetSolutionScope(data.Solution)}",
                $"Loss: {GetLossMetadata(data.Solution)}"
            };

            if (data.Solution == null) return parameters.ToArray();

            var reportParameters = data.Solution.ReportParameters ?? new Dictionary<ParameterType, FloatWithError>();
            var ordered = new List<KeyValuePair<ParameterType, FloatWithError>>();

            foreach (var key in PdfMetadataParameterOrder)
            {
                if (reportParameters.ContainsKey(key))
                {
                    ordered.Add(new KeyValuePair<ParameterType, FloatWithError>(key, reportParameters[key]));
                    continue;
                }

                if (data.Solution.Parameters.ContainsKey(key))
                {
                    ordered.Add(new KeyValuePair<ParameterType, FloatWithError>(key, data.Solution.Parameters[key]));
                }
            }

            foreach (var par in ordered)
            {
                parameters.Add($"{GetParameterMetadataLabel(par.Key)} = {FormatParameterMetadataValue(par.Key, par.Value)}");
            }

            return parameters.ToArray();
        }

        static string GetModelMetadata(ExperimentData data)
        {
            if (data?.Solution == null) return "";

            return data.Solution.ModelType.GetProperties()?.Name ?? data.Solution.ModelType.ToString();
        }

        static string GetSolutionScope(SolutionInterface solution)
        {
            if (solution == null) return "";

            return solution.IsGlobalAnalysisSolution ? "Global" : "Single";
        }

        static string GetLossMetadata(SolutionInterface solution)
        {
            if (solution == null) return "";

            return solution.Loss.ToString("G3");
        }

        static string GetParameterMetadataLabel(ParameterType key)
        {
            return key switch
            {
                ParameterType.Nvalue1 => "N",
                ParameterType.Nvalue2 => "N2",
                ParameterType.Affinity1 => "Kd",
                ParameterType.Affinity2 => "Kd2",
                ParameterType.ApparentAffinity => "Kd app",
                ParameterType.Enthalpy1 => "ΔH",
                ParameterType.Enthalpy2 => "ΔH2",
                ParameterType.EntropyContribution1 => "-TΔS",
                ParameterType.EntropyContribution2 => "-TΔS2",
                ParameterType.Gibbs1 => "ΔG",
                ParameterType.Gibbs2 => "ΔG2",
                ParameterType.HeatCapacity1 => "ΔCp",
                ParameterType.HeatCapacity2 => "ΔCp2",
                ParameterType.IsomerizationEquilibriumConstant => "Keq",
                ParameterType.IsomerizationRate => "kiso",
                ParameterType.CisIsomerPopulationPercentage => "%cis",
                _ => key.GetProperties().Name
            };
        }

        static string FormatParameterMetadataValue(ParameterType key, FloatWithError value)
        {
            var parent = key.GetProperties().ParentType;
            var energyUnit = AppClasses.AnalysisClasses.Models.Model.ReportEnergyUnit;

            return parent switch
            {
                ParameterType.Affinity1 => value.AsFormattedConcentration(withunit: true),
                ParameterType.Enthalpy1 => value.Energy.ToFormattedString(energyUnit, permole: true),
                ParameterType.EntropyContribution1 => value.Energy.ToFormattedString(energyUnit, permole: true),
                ParameterType.Gibbs1 => value.Energy.ToFormattedString(energyUnit, permole: true),
                ParameterType.Offset => value.Energy.ToFormattedString(energyUnit, permole: true),
                ParameterType.HeatCapacity1 => value.Energy.ToFormattedString(energyUnit, permole: true, perK: true),
                _ => value.AsNumber(),
            };
        }

        void InitializeGraph()
        {
            if (StateManager.CurrentState != ProgramState.Publish) return;
            if (DataManager.Current == null) return;
            graph = new FinalFigure(DataManager.Current, this)
            {
                PlotDimensions = new CGSize(Width, Height),
                SanitizeTicks = SanitizeTicks,

                PowerAxisTitle = PowerAxisTitle,
                TimeAxisTitle = TimeAxisTitle,
                UseUnifiedDataAxes = UnifiedPowerAxis,
                ShouldDrawBaseline = DrawBaseline,
                DrawBaselineCorrected = DrawBaselineCorrected,

                EnthalpyAxisTitle = EnthalpyAxisTitle,
                MolarRatioAxisTitle = MolarRatioAxisTitle,
                UseUnifiedAnalysisAxes = UseUnifiedMolarRatioAxis,
                UnifiedEnthalpyAxis = UnifiedEnthalpyAxis,
                ShowBadDataPoints = ShowBadData,
                ShowBadDataErrorBars = ShowBadDataErrorBars,
                ShowErrorBars = ShowErrorBars,
                DrawConfidence = DrawConfidence,
                DrawZeroLine = DrawZeroLine,
                DrawFitParameters = DrawFitParameters,
                DrawExpDetails = DrawFitParameters, //TODO implement separate option
                FinalFigureDisplayParameters = AppSettings.FinalFigureParameterDisplay,
                SymbolShape = (CGGraph.SymbolShape)SymbolShape,
                SymbolSize = SymbolSize,
                ShowResiduals = ShowResiduals,
                IncludeResidualGraphGap = GapResidualGraph,
                LineSmoothness = FitLineSmoothness,
                AutoAxesIgnoresBadData = AutoAxesIgnoresBadData,
                ShowDataGraph = ShowDataGraph,
            };

            graph.SetTimeUnit(TimeAxisUnit);
            graph.SetEnergyUnit(EnergyUnit);
            graph.SetTickNumber(DataXTickCount, DataYTickCount, FitXTickCount, FitYTickCount);
            graph.SetShowDataGraph(ShowDataGraph);

            SetFrameSize(graph.PrintBox.Size); 

            PlotSizeChanged?.Invoke(graph, null);
        }

        public void Export()
        {
            //Print(this);

            var path = NSFileManager.DefaultManager.GetUrl(NSSearchPathDirectory.DesktopDirectory, NSSearchPathDomain.All, NSUrl.FromFilename("test.pdf"), true, out NSError error);

            var url = NSUrl.FromFilename(new NSUrl("test.pdf", path.Path).Path);

            var x = new CGContextPDF(url);
            x.BeginPage(graph.PrintBox);

            graph.Draw(x, new CGPoint(Frame.Width / 2, Frame.Height / 2));
            x.EndPage();
            x.Close();
        }

        public override void DrawRect(CGRect dirtyRect)
        {
            if (StateManager.CurrentState != ProgramState.Publish) return;
            if (DataManager.Current == null) return;
            if (graph == null) { InitializeGraph(); }

            base.DrawRect(dirtyRect);

            var cg = NSGraphicsContext.CurrentContext.CGContext;

            graph.Draw(cg, new CGPoint(Frame.Width / 2, Frame.Height / 2));
        }

        public void Print()
        {
            var scalingfactor = 1 / 1.576f;

            var op = NSPrintOperation.FromView(this);
            op.PrintInfo.PaperSize = this.Frame.Size.ScaleBy(scalingfactor);
            op.PrintInfo.BottomMargin = 0;
            op.PrintInfo.TopMargin = 0;
            op.PrintInfo.LeftMargin = 0;
            op.PrintInfo.RightMargin = 0;
            op.PrintInfo.ScalingFactor = scalingfactor;
            op.RunOperation();
        }
    }
}
