// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace AnalysisITC
{
	public partial class TemperatureDependenceGraphView : NSGraph
	{
        TemperatureDependenceGraph TemperatureDependenceGraph { get; set; } = null;
        ThermodynamicParameterBarPlot RawParameterBarPlot { get; set; } = null;

        new GraphBase Graph => TemperatureDependenceGraph == null ? RawParameterBarPlot : TemperatureDependenceGraph;

		public TemperatureDependenceGraphView (IntPtr handle) : base (handle)
		{
            AppSettings.SettingsDidUpdate += AppSettings_SettingsDidUpdate;
        }

        private void AppSettings_SettingsDidUpdate(object sender, EventArgs e)
        {
            Invalidate();
        }

        public void Initialize(AnalysisResult r)
        {
            TemperatureDependenceGraph = null;
            RawParameterBarPlot = null;

            if (r.Solution.Model.TemperatureDependenceExposed)
            {
                TemperatureDependenceGraph = new TemperatureDependenceGraph(r, this);
            }
            else RawParameterBarPlot = new ThermodynamicParameterBarPlot(r, this);

            Invalidate();
        }

        public override void DrawRect(CGRect dirtyRect)
        {
            base.DrawRect(dirtyRect);

            var cg = NSGraphicsContext.CurrentContext.CGContext;

            if (TemperatureDependenceGraph != null) TemperatureDependenceGraph.PrepareDraw(cg, new CGPoint(Frame.GetMidX(), Frame.GetMidY()));
            else if (RawParameterBarPlot != null) RawParameterBarPlot.PrepareDraw(cg, new CGPoint(Frame.GetMidX(), Frame.GetMidY()));
        }

        new public void Print()
        {
            var _drawOnWhite = Graph.DrawOnWhite;
            Graph.DrawOnWhite = true;

            Invalidate();

            var op = NSPrintOperation.FromView(this);
            op.PrintInfo.PaperSize = this.Frame.Size;
            op.PrintInfo.BottomMargin = 0;
            op.PrintInfo.TopMargin = 0;
            op.PrintInfo.LeftMargin = 0;
            op.PrintInfo.RightMargin = 0;
            op.PrintInfo.ScalingFactor = 1;
            op.RunOperation();

            Graph.DrawOnWhite = _drawOnWhite;
        }
    }
}
