<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AnalysisITC.Core\AnalysisITC.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\AnalysisITC.MacOS\Assets.xcassets\AppIcon.iconset\icon_32x32.png"
             Link="wwwroot\assets\ft-itc-icon-32.png"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\AnalysisITC.MacOS\Assets.xcassets\AppIcon.iconset\icon_32x32@2x.png"
             Link="wwwroot\assets\ft-itc-icon-64.png"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\AnalysisITC.MacOS\Assets.xcassets\AppIcon.iconset\icon_128x128@2x.png"
             Link="wwwroot\assets\ft-itc-icon-256.png"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ReleaseVersion>1.1</ReleaseVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
</Project>
