// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC.UI.MacOS
{
	public partial class AnalysisGlobalModeOptionsViewController : NSViewController
	{
		public AnalysisGlobalModeOptionsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
