// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using Foundation;
using AppKit;

using AnalysisITC.Core.Application;
using AnalysisITC.Core.Analysis;
using AnalysisITC.Core.Analysis.Models;
using AnalysisITC.Core.Data;
using AnalysisITC.Core.DataReaders;
using AnalysisITC.Core.Export;
using AnalysisITC.Core.Numerics;
using AnalysisITC.Core.Presentation;
using AnalysisITC.Core.Processing;
using AnalysisITC.Core.Units;
using AnalysisITC.Core.Utilities;

namespace AnalysisITC
{
	public partial class GuideHintViewController : NSViewController
	{
		public GuideHintViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();
        }

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            var img = NSImage.ImageNamed("ExperimentViewCell");


            ImageView.Image = img;
        }
    }
}
