// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using System.Collections.Generic;

using AnalysisITC.Core.Application;
using AnalysisITC.Core.Analysis;
using AnalysisITC.Core.Analysis.Models;
using AnalysisITC.Core.Data;
using AnalysisITC.Core.DataReaders;
using AnalysisITC.Core.Export;
using AnalysisITC.Core.Numerics;
using AnalysisITC.Core.Presentation;
using AnalysisITC.Core.Processing;
using AnalysisITC.Core.Units;
using AnalysisITC.Core.Utilities;

namespace AnalysisITC
{
	public partial class HelpViewController : NSViewController
	{
        public static Dictionary<int, string[]> ContentIndexes;
        HelpDocumentView helpDocumentView;

		public HelpViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            helpDocumentView = new HelpDocumentView(this, HelpTextField, "./HelpTextResource.txt");
            helpDocumentView.Install();
        }

        public void Index()
        {

        }

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();
        }
    }
}
