// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AnalysisITC
{
	public partial class AboutAppViewController : NSViewController
	{
		public AboutAppViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            VersionButton.Title = $"Version: {AppVersion.ShortVersionString}";
        }

        partial void VersionLabelClick(NSObject sender)
        {

        }

        partial void VersionButtonAction(NSObject sender)
        {
            VersionButton.Title = $"Version: {AppVersion.FullVersionString}";
        }
    }
}
