// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using AppKit;
using AnalysisITC.AppClasses.Analysis2;
using AnalysisITC.Utilities;

namespace AnalysisITC
{
	public partial class BindingAnalysisViewController : NSViewController
	{
        public static event EventHandler UpdateTable;

        public static AnalysisResult AnalysisResult { get; set; }

        EnergyUnit EnergyUnit => (int)EnergyUnitControl.SelectedSegment switch { 0 => EnergyUnit.Joule, 1 => EnergyUnit.KiloJoule, 2 => EnergyUnit.Cal, 3 => EnergyUnit.KCal, _ => EnergyUnit.KiloJoule, };
        public bool UseKelvin => TemperatureUnitControl.SelectedSegment == 1;

        public BindingAnalysisViewController (IntPtr handle) : base (handle)
		{
            
		}

        public override void ViewDidAppear()
        {
            Graph.Initialize(AnalysisResult);

            Setup();
        }

        void Setup()
        {
            string fit = "";
            string parameters = "";
            string parameter_values = "";

            if (this.NextResponder is NSWindow) (this.NextResponder as NSWindow).Title = AnalysisResult.FileName;

            NameTextField.StringValue = AnalysisResult.FileName;
            CommentTextField.StringValue = AnalysisResult.Comments;

            fit += AnalysisResult.Solution.Solutions.Count + " experiments" + Environment.NewLine;
            fit += AnalysisResult.Solution.SolutionName + Environment.NewLine;
            fit += Extensions.GetEnumDescription(AnalysisResult.Solution.Convergence.Algorithm) + Environment.NewLine;
            fit += AnalysisResult.Solution.Convergence.Iterations + " | " + AnalysisResult.Solution.Loss.ToString("G3") + " | " + AnalysisResult.Solution.Convergence.Time.TotalMilliseconds.ToString("F0") + "ms" + Environment.NewLine;
            fit += AnalysisResult.Solution.BootstrapIterations + " | " + AnalysisResult.Solution.BootstrapTime.TotalSeconds.ToString("F1") + "s" + Environment.NewLine;
            fit += (AnalysisResult.Solution.WeightedFitting ? "ENABLED" : "OFF") + " | " + (AnalysisResult.Solution.ModelCloneOptions.IncludeConcentrationErrorsInBootstrap ? "ENABLED" : "OFF");

            // Constraints
            if (AnalysisResult.Solution.Model.Parameters.Constraints.Count > 0)
            {
                ConstraintLabel.StringValue = "";
                ConstraintKeyLabel.StringValue = "";

                foreach (var con in AnalysisResult.Solution.Model.Parameters.Constraints)
                {
                    ConstraintLabel.StringValue += con.Value.GetEnumDescription() + Environment.NewLine;
                    ConstraintKeyLabel.StringValue += con.Key.GetEnumDescription() + ":" + Environment.NewLine;
                }

                ConstraintLabel.StringValue = ConstraintLabel.StringValue.Trim();
                ConstraintKeyLabel.StringValue = ConstraintKeyLabel.StringValue.Trim();
            }
            else
            {
                ConstraintLabel.StringValue = "";
                ConstraintKeyLabel.StringValue = "No constraints";
            }

            parameters += AnalysisResult.Solution.Model.MeanTemperature.ToString("F3") + " °C";

            FitParameterLabel.StringValue = fit;
            //DataSetParameterLabel.StringValue = parameters;

            var items = AnalysisResult.GetParameterEvaluationList();

            // Left column labels

            var attr = MacStrings.FromMarkDownString(string.Join(Environment.NewLine, items.Select(i => i.Item1 + ":")), NSFont.SystemFontOfSize(11));
            var mutable = new NSMutableAttributedString(attr);
            var full = new NSRange(0, mutable.Length);
            // Preserve existing paragraph style if present, but override alignment
            var existing = mutable.GetAttribute(NSStringAttributeKey.ParagraphStyle, 0, out _) as NSParagraphStyle;
            var ps = existing != null ? (existing.MutableCopy() as NSMutableParagraphStyle) : new NSMutableParagraphStyle();
            ps.Alignment = NSTextAlignment.Right;

            mutable.AddAttribute(NSStringAttributeKey.ParagraphStyle, ps, full);

            ParameterLabels.AttributedStringValue = mutable;

            // Right column values
            DataSetParameterLabel.StringValue =
                string.Join(Environment.NewLine, items.Select(i => i.Item2));
        }

        partial void CopyToClipboard(NSObject sender)
        {
            Exporter.CopyToClipboard(AnalysisResult, AppSettings.DefaultConcentrationUnit, EnergyUnit, UseKelvin);
        }

        partial void LoadSolutionsToExperiments(NSObject sender)
        {
            StatusBarManager.SetStatus("Copying solutions to experiments...");

            foreach (var sol in AnalysisResult.Solution.Solutions)
            {
                sol.Data.UpdateSolution(sol.Model);
            }

            StatusBarManager.ClearAppStatus();
            StatusBarManager.SetStatus("Solutions updated", 2000);

            DataAnalysisViewController.InvalidateGraph();
        }

        partial void CloseButtonClicked(NSObject sender)
        {
            if (this.NextResponder is NSWindow)
            {
                var window = this.NextResponder as NSWindow;

                if (window.IsSheet) DismissViewController(this);
                else window.Close();
            }
        }

        partial void Apply(NSObject sender)
        {
            if (!string.IsNullOrWhiteSpace(NameTextField.StringValue))
                AnalysisResult.FileName = NameTextField.StringValue;

            if (!string.IsNullOrWhiteSpace(CommentTextField.StringValue))
                AnalysisResult.Comments = CommentTextField.StringValue;

            CloseButtonClicked(sender);

            UpdateTable?.Invoke(this, null);
        }
    }
}
