// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using AppKit;
using AnalysisITC.AppClasses.Analysis2;
using AnalysisITC.Utilities;

namespace AnalysisITC
{
	public partial class BindingAnalysisViewController : NSViewController
	{
        public static event EventHandler UpdateTable;

        private AnalysisResult Result { get; set; }

        EnergyUnit EnergyUnit => (int)EnergyUnitControl.SelectedSegment switch { 0 => EnergyUnit.Joule, 1 => EnergyUnit.KiloJoule, 2 => EnergyUnit.Cal, 3 => EnergyUnit.KCal, _ => EnergyUnit.KiloJoule, };
        public bool UseKelvin => TemperatureUnitControl.SelectedSegment == 1;

        public void SetResult(AnalysisResult result) => Result = result;

        public BindingAnalysisViewController (IntPtr handle) : base (handle)
		{
            
		}

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            // Remove detach view button if alrady detached
            if (this.NextResponder is NSWindow window)
            {
                if (!window.IsSheet) DetachViewButton.Hidden = true;
            }

            Graph.Initialize(Result);

            Setup();
        }

        void Setup()
        {
            string info = "";

            if (this.NextResponder is NSWindow) (this.NextResponder as NSWindow).Title = Result.FileName;

            NameTextField.StringValue = Result.FileName;
            CommentTextField.StringValue = Result.Comments;

            info += Result.Solution.Solutions.Count + " experiments" + Environment.NewLine;
            info += Result.Solution.SolutionName + Environment.NewLine;
            info += Extensions.GetEnumDescription(Result.Solution.Convergence.Algorithm) + Environment.NewLine;
            info += Result.Solution.Convergence.Iterations + " | " + Result.Solution.Loss.ToString("G3") + " | " + Result.Solution.Convergence.Time.TotalMilliseconds.ToString("F0") + "ms" + Environment.NewLine;
            info += Result.Solution.BootstrapIterations + " | " + Result.Solution.BootstrapTime.TotalSeconds.ToString("F1") + "s" + Environment.NewLine;
            info += (Result.Solution.UseWeightedFitting ? "ENABLED" : "OFF") + " | " + (Result.Solution.ModelCloneOptions.IncludeConcentrationErrorsInBootstrap ? "ENABLED" : "OFF") + Environment.NewLine;
            info += Result.UIShortDateWithTime;

            FitParameterLabel.StringValue = info;

            var items = Result.GetParameterEvaluationList();

            // Left column labels
            var attr = MacStrings.FromMarkDownString(string.Join(Environment.NewLine, items.Select(i => i.Item1 + ":")), NSFont.SystemFontOfSize(11));
            var mutable = new NSMutableAttributedString(attr);
            var full = new NSRange(0, mutable.Length);
            // Preserve existing paragraph style if present, but override alignment
            var existing = mutable.GetAttribute(NSStringAttributeKey.ParagraphStyle, 0, out _) as NSParagraphStyle;
            var ps = existing != null ? (existing.MutableCopy() as NSMutableParagraphStyle) : new NSMutableParagraphStyle();
            ps.Alignment = NSTextAlignment.Right;

            mutable.AddAttribute(NSStringAttributeKey.ParagraphStyle, ps, full);

            ParameterLabels.AttributedStringValue = mutable;

            // Right column values
            DataSetParameterLabel.AttributedStringValue =
                MacStrings.FromMarkDownString(string.Join(Environment.NewLine, items.Select(i => i.Item2)), NSFont.SystemFontOfSize(11));
        }

        partial void CopyToClipboard(NSObject sender)
        {
            Exporter.CopyToClipboard(Result, AppSettings.DefaultConcentrationUnit, EnergyUnit, UseKelvin);
        }

        partial void PopView(NSObject sender)
        {
            var storyboard = NSStoryboard.FromName("Main", null);
            var vc = storyboard.InstantiateControllerWithIdentifier("BindingAnalysisViewController")
                     as BindingAnalysisViewController;

            var wc = storyboard.InstantiateControllerWithIdentifier("DetachedAnalysisResultWindowController") as NSWindowController;

            (wc.ContentViewController as BindingAnalysisViewController).SetResult(Result);

            wc.ShowWindow(null);

            CloseButtonClicked(sender);
        }

        partial void LoadSolutionsToExperiments(NSObject sender)
        {
            StatusBarManager.SetStatus("Copying solutions to experiments...");

            foreach (var sol in Result.Solution.Solutions)
            {
                sol.Data.UpdateSolution(sol.Model);
            }

            StatusBarManager.ClearAppStatus();
            StatusBarManager.SetStatus("Solutions updated", 2000);

            DataAnalysisViewController.InvalidateGraph();
        }

        partial void CloseButtonClicked(NSObject sender)
        {
            if (this.NextResponder is NSWindow window)
            {
                if (window.IsSheet) DismissViewController(this);
                else window.Close();
            }
        }

        partial void EnableSolutionExperiments(NSObject sender)
        {
            var solutionexp = Result.Solution.Model.Models.Select(m => m.Data.UniqueID);

            DataManager.Data.ForEach(d => d.Include = solutionexp.Contains(d.UniqueID));

            UpdateTable?.Invoke(this, null);
        }

        partial void Apply(NSObject sender)
        {
            if (!string.IsNullOrWhiteSpace(NameTextField.StringValue))
                Result.FileName = NameTextField.StringValue;

            if (!string.IsNullOrWhiteSpace(CommentTextField.StringValue))
                Result.Comments = CommentTextField.StringValue;

            CloseButtonClicked(sender);

            UpdateTable?.Invoke(this, null);
        }
    }
}
