// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace AnalysisITC
{
	public partial class TabControllerView : NSView
	{
		public TabControllerView (IntPtr handle) : base (handle)
		{
		}

        public override void DrawRect(CGRect dirtyRect)
        {
            base.DrawRect(dirtyRect);

            var cg = NSGraphicsContext.CurrentContext.CGContext;

            cg.SetFillColor(NSColor.Separator.CGColor);
            cg.FillRect(Bounds);
        }
    }
}
